import {createHash} from 'node:crypto';
export const jointNames=['pelvis','right_hip','right_knee','right_ankle','left_hip','left_knee','left_ankle','spine','neck','nose','head','left_shoulder','left_elbow','left_wrist','right_shoulder','right_elbow','right_wrist'];
const num={type:'number'},str={type:'string',minLength:1},sha={type:'string',pattern:'^[a-f0-9]{64}$'},array=(items,minItems=1,maxItems=10000)=>({type:'array',items,minItems,maxItems}),tuple=(n)=>array(num,n,n),obj=(properties)=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false}),constant=v=>({const:v});
const base={schemaVersion:constant(1)},window=tuple(2),frame2=obj({sourceTime:num,keypoints:array(tuple(3),17,17)});
export const schemas={
 reference:obj({...base,kind:constant('human-video-reference'),sourceSHA256:sha,window,video:obj({file:str,sha256:sha,duration:num,timeOrigin:constant('trim-start')}),person:obj({selection:str,mirroring:{enum:['unknown','mirrored','unmirrored']},anatomicalLabels:constant('estimated')}),observations:obj({skeleton:constant('COCO17'),coordinates:constant('source-pixels-xy-confidence'),detectorSHA256:sha,frames:array(frame2,2,10000)}),phases:array(obj({name:str,start:num,end:num})),unknowns:array(str)}),
 motion:obj({...base,kind:constant('estimated-human-motion'),sourceSHA256:sha,window,skeleton:constant('H36M17'),jointNames:array(str,17,17),coordinates:constant('camera-x-right-y-down-z-depth-root-relative'),units:constant('normalized-estimated-not-meters'),sourceTimes:array(num,2,256),positions:array(array(tuple(3),17,17),2,256),imagePelvis:array(tuple(2),2,256),backend:obj({name:str,checkpointSHA256:sha,codeCommit:str}),fitting:obj({algorithm:str,assumptions:array(str)}),unknowns:array(str)}),
 bundle:obj({...base,kind:constant('video-motion-review-bundle'),status:constant('draft-unreviewed'),artifacts:obj(Object.fromEntries(['reference','motion','video','action','quality','rawEstimate'].map(k=>[k,obj({file:str,sha256:sha,bytes:{type:'integer',minimum:1}})]))),action:obj({id:str,revision:{type:'integer',minimum:1},rig:str,motionHash:sha}),sync:obj({actionDuration:num,sourceWindow:window,anchors:array(obj({actionTime:num,sourceTime:num,videoTime:num}),2,32),mapping:constant('piecewise-linear')}),cacheKeys:obj({observation:sha,estimation:sha,fitting:sha,retarget:sha}),contactStatus:constant('unconfirmed'),reviewWindows:array(tuple(2),0,128)})
};
export function validateSchema(value,schema,path='$'){
 const fail=m=>{throw Error(path+': '+m)};
 if('const' in schema&&value!==schema.const)fail('wrong constant');if(schema.enum&&!schema.enum.includes(value))fail('invalid enum');
 if(schema.type==='object'){if(!value||typeof value!=='object'||Array.isArray(value))fail('expected object');for(const k of schema.required)if(!Object.hasOwn(value,k))fail('missing '+k);for(const k of Object.keys(value)){if(!schema.properties[k])fail('unknown '+k);validateSchema(value[k],schema.properties[k],path+'.'+k);}}
 if(schema.type==='array'){if(!Array.isArray(value)||value.length<schema.minItems||value.length>schema.maxItems)fail('invalid array length');value.forEach((v,i)=>validateSchema(v,schema.items,path+'['+i+']'));}
 if(schema.type==='number'||schema.type==='integer'){if(typeof value!=='number'||!Number.isFinite(value)||schema.type==='integer'&&!Number.isInteger(value)||schema.minimum!==undefined&&value<schema.minimum)fail('invalid number');}
 if(schema.type==='string'&&(typeof value!=='string'||value.length<(schema.minLength||0)||schema.pattern&&!new RegExp(schema.pattern).test(value)))fail('invalid string');
 return value;
}
const ascending=x=>x.every((t,i)=>i===0||t>x[i-1]);
export function validateReference(r){validateSchema(r,schemas.reference);if(r.window[1]<=r.window[0]||Math.abs(r.video.duration-(r.window[1]-r.window[0]))>1e-6)throw Error('Reference duration mismatch');const ts=r.observations.frames.map(f=>f.sourceTime);if(!ascending(ts)||ts[0]<r.window[0]-1e-6||ts.at(-1)>r.window[1]+1e-6)throw Error('Invalid observation timestamps');for(const f of r.observations.frames)for(const p of f.keypoints)if(p[2]<0||p[2]>1)throw Error('Invalid confidence');let end=0;for(const p of r.phases){if(Math.abs(p.start-end)>1e-6||p.end<=p.start)throw Error('Noncontiguous phases');end=p.end;}if(Math.abs(end-r.video.duration)>1e-6)throw Error('Phase duration mismatch');return r;}
export function validateMotion(m){validateSchema(m,schemas.motion);if(JSON.stringify(m.jointNames)!==JSON.stringify(jointNames))throw Error('Joint order mismatch');if(!ascending(m.sourceTimes)||m.positions.length!==m.sourceTimes.length||m.imagePelvis.length!==m.sourceTimes.length||Math.abs(m.sourceTimes[0]-m.window[0])>1e-6||Math.abs(m.sourceTimes.at(-1)-m.window[1])>1e-6)throw Error('Motion timestamps mismatch');return m;}
export function canonical(x){if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';if(x&&typeof x==='object')return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';return JSON.stringify(x);}
export const digest=x=>createHash('sha256').update(typeof x==='string'||Buffer.isBuffer(x)?x:canonical(x)).digest('hex');
export function sourceTimeAt(sync,t){if(!Number.isFinite(t)||t<0||t>sync.actionDuration)throw Error('Action time outside sync window');const a=sync.anchors;for(let i=1;i<a.length;i++)if(t<=a[i].actionTime){const p=a[i-1],q=a[i],ratio=(t-p.actionTime)/(q.actionTime-p.actionTime);return p.sourceTime+ratio*(q.sourceTime-p.sourceTime);}throw Error('Invalid anchors');}
export function validateBundle(b,r,m){validateSchema(b,schemas.bundle);validateReference(r);validateMotion(m);if(b.artifacts.video.file!==r.video.file||b.artifacts.video.sha256!==r.video.sha256||r.sourceSHA256!==m.sourceSHA256||JSON.stringify(r.window)!==JSON.stringify(m.window)||JSON.stringify(b.sync.sourceWindow)!==JSON.stringify(r.window))throw Error('Bundle source mismatch');const a=b.sync.anchors;if(!ascending(a.map(x=>x.actionTime))||!ascending(a.map(x=>x.sourceTime))||!ascending(a.map(x=>x.videoTime)))throw Error('Invalid sync anchors');if(a[0].actionTime!==0||a[0].videoTime!==0||Math.abs(a[0].sourceTime-r.window[0])>1e-6||Math.abs(a.at(-1).actionTime-b.sync.actionDuration)>1e-6||Math.abs(a.at(-1).sourceTime-r.window[1])>1e-6)throw Error('Sync endpoint mismatch');for(const x of a)if(Math.abs(x.videoTime-(x.sourceTime-r.window[0]))>1e-6)throw Error('Video/source time mismatch');for(const w of b.reviewWindows)if(w[0]<0||w[1]<=w[0]||w[1]>b.sync.actionDuration+1e-6)throw Error('Invalid review window');for(const x of Object.values(b.artifacts))if(!/^[a-zA-Z0-9_.-]+$/.test(x.file)||x.file==='..')throw Error('Unsafe artifact path');return b;}
