import * as T from 'three/webgpu';
import {Action,validateAction} from '../../runtime/action';
// Specific H36M17 -> Quaternius adapter. No joint positions/scales are authored.
export function bodyFrame(left:T.Vector3,right:T.Vector3,up:T.Vector3){const x=left.clone().sub(right).normalize(),y=up.clone().addScaledVector(x,-up.dot(x)).normalize();if(x.lengthSq()<.9||y.lengthSq()<.9)throw Error('Degenerate body frame');const z=new T.Vector3().crossVectors(x,y).normalize();return new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(x,y,z));}
// Torso frame: the pelvis-to-neck direction is kept exactly and the shoulder line is squared to it. Squaring the spine to
// the shoulders instead would remove any sideways lean whenever the shoulders stay level.
export function torsoFrame(left:T.Vector3,right:T.Vector3,up:T.Vector3){const y=up.clone().normalize(),across=left.clone().sub(right),x=across.addScaledVector(y,-across.dot(y)).normalize();if(y.lengthSq()<.9||x.lengthSq()<.9)throw Error('Degenerate torso frame');const z=new T.Vector3().crossVectors(x,y).normalize();return new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(x,y,z));}
// With parentRestWorld, the limb first turns with its parent (so knees and elbows keep facing the way the body faces through a
// spin) and then swings the shortest way onto the target direction. Without it, the swing starts from the rest pose in world space.
export function localForDirection(parentWorld:T.Quaternion,restWorld:T.Quaternion,restDirection:T.Vector3,direction:T.Vector3,parentRestWorld?:T.Quaternion){if(direction.lengthSq()<1e-10)throw Error('Degenerate limb direction');const carried=parentRestWorld?parentWorld.clone().multiply(parentRestWorld.clone().invert()):new T.Quaternion(),world=new T.Quaternion().setFromUnitVectors(restDirection.clone().normalize().applyQuaternion(carried),direction.clone().normalize()).multiply(carried).multiply(restWorld);return parentWorld.clone().invert().multiply(world).normalize();}
export function retarget(model:T.Object3D,positions:number[][][],times:number[],imagePelvis:number[][],pixelScale:number,id='video-side-kick-draft',options?:{name:string,airborne?:boolean,lowestAnkleImageY?:number[],faceDirection?:number[][],phases?:{name:string,end:number,kind?:'move'|'fast'|'hold'}[]}){
 if(positions.length!==times.length||times.length<2||times.length>256||positions.some(f=>f.length!==17||f.some(p=>p.length!==3||p.some(x=>!Number.isFinite(x)))))throw Error('Invalid estimated motion');
 if(imagePelvis.length!==times.length||imagePelvis.some(p=>p.length!==2||p.some(x=>!Number.isFinite(x)))||!Number.isFinite(pixelScale)||pixelScale<=0)throw Error('Invalid image trajectory');
 const start=times[0],total=times.at(-1)!-start;if(total<=0||times.some((t,i)=>!Number.isFinite(t)||i>0&&t<=times[i-1]))throw Error('Invalid times');
 if(!options&&Math.abs(total-2.3)>1e-6)throw Error('Pilot adapter requires the 2.3-second side-kick window');
 const bones:T.Object3D[]=[];model.traverse(b=>{if((b as T.Bone).isBone)bones.push(b)});const depth=(b:T.Object3D):number=>b.parent?1+depth(b.parent):0;bones.sort((a,b)=>depth(a)-depth(b));model.updateMatrixWorld(true);
 const get=(n:string)=>{const b=model.getObjectByName(n);if(!b)throw Error('Missing bone '+n);return b;},point=(n:string)=>get(n).getWorldPosition(new T.Vector3());
 const restFrame=bodyFrame(point('thigh_l'),point('thigh_r'),point('neck_01').sub(point('pelvis'))),restTorso=options?torsoFrame(point('upperarm_l'),point('upperarm_r'),point('neck_01').sub(point('pelvis'))):restFrame;
 const limbMap:Record<string,[number,number,string]>={thigh_r:[1,2,'calf_r'],calf_r:[2,3,'foot_r'],thigh_l:[4,5,'calf_l'],calf_l:[5,6,'foot_l'],upperarm_l:[11,12,'lowerarm_l'],lowerarm_l:[12,13,'hand_l'],upperarm_r:[14,15,'lowerarm_r'],lowerarm_r:[15,16,'hand_r']};
 const rest=bones.map(b=>({b,q:b.quaternion.clone(),world:b.getWorldQuaternion(new T.Quaternion()),direction:limbMap[b.name]?point(limbMap[b.name][2]).sub(b.getWorldPosition(new T.Vector3())):null}));
 const carry=new Map<T.Object3D,{parent:T.Quaternion,world:T.Quaternion,direction:T.Vector3}>();const restWorlds=new Map<T.Object3D,T.Quaternion>();model.traverse(o=>{restWorlds.set(o,o.getWorldQuaternion(new T.Quaternion()));});const tracks:Action['tracks']=bones.map(b=>({target:b.name,property:'rotation',mode:'absolute',interpolation:'linear',keys:[]}));const rootTrack:NonNullable<Action['tracks']>[number]={target:'$root',property:'position',mode:'absolute',interpolation:'linear',keys:[]};
 const scale=new T.Vector3();model.getWorldScale(scale);const worldScale=scale.x;const solid:{time:number,inside:number,pair:string}[]=[];const span=(a:string,b:string)=>Math.round(point(a).distanceTo(point(b))/worldScale*1000)/1000,rigProportions={hipWidth:span('thigh_l','thigh_r'),shoulderWidth:span('upperarm_l','upperarm_r'),pelvisToNeck:span('pelvis','neck_01'),neckToHead:span('neck_01','Head'),thigh:span('thigh_l','calf_l'),shin:span('calf_l','foot_l'),upperArm:span('upperarm_l','lowerarm_l'),forearm:span('lowerarm_l','hand_l'),hipInPelvisFrame:point('thigh_l').sub(point('pelvis')).divideScalar(worldScale).applyQuaternion(restFrame.clone().invert()).toArray().map(x=>Math.round(x*1000)/1000),neckInTorsoFrame:point('neck_01').sub(point('pelvis')).divideScalar(worldScale).applyQuaternion(restTorso.clone().invert()).toArray().map(x=>Math.round(x*1000)/1000),shoulderInTorsoFrame:point('upperarm_l').sub(point('neck_01')).divideScalar(worldScale).applyQuaternion(restTorso.clone().invert()).toArray().map(x=>Math.round(x*1000)/1000),headInTorsoFrame:point('Head').sub(point('neck_01')).divideScalar(worldScale).applyQuaternion(restTorso.clone().invert()).toArray().map(x=>Math.round(x*1000)/1000),hipBelowPelvis:Math.round((point('pelvis').y-point('thigh_l').y)/worldScale*1000)/1000,shoulderBelowNeck:Math.round((point('neck_01').y-point('upperarm_l').y)/worldScale*1000)/1000};
 // Joint ranges (R27). Textbook adult ranges in degrees; see docs/RULE_LOG.md for sources. Knee and elbow are enforced elsewhere;
 // the rest are only reported, because trained performers pass the hip figures in every split and high kick.
 const restForward=new T.Vector3(0,0,1).applyQuaternion(restFrame),deg=180/Math.PI,ranges:Record<string,{limit:number,peak:number,time:number,beyond:number}>={};
 const note=(key:string,limit:number,value:number,time:number)=>{const e=ranges[key]??={limit,peak:-Infinity,time:0,beyond:0};if(value>e.peak){e.peak=value;e.time=time;}if(value>limit)e.beyond++;};
 const twist=(q:T.Quaternion,axis:T.Vector3)=>{const a=2*Math.atan2(new T.Vector3(q.x,q.y,q.z).dot(axis),q.w)*deg;return Math.abs(((a+540)%360)-180);};
 positions.forEach((frame,i)=>{
  // Camera x-right/y-down/z-away -> Three x-right/y-up/z-toward camera.
  const p=frame.map(v=>new T.Vector3(v[0],-v[1],-v[2]));const hipFrame=bodyFrame(p[4],p[1],p[8].clone().sub(p[0])),torso=options?torsoFrame(p[11],p[14],p[8].clone().sub(p[0])):bodyFrame(p[11],p[14],p[8].clone().sub(p[0]));
  model.position.set(0,0,0);model.updateMatrixWorld(true);
  for(let j=0;j<rest.length;j++){
   const r=rest[j],b=r.b,parent=b.parent!.getWorldQuaternion(new T.Quaternion());let q=r.q.clone();
   if(b.name==='pelvis'||['spine_01','spine_02','spine_03'].includes(b.name))q=parent.clone().invert().multiply((b.name==='pelvis'?hipFrame.clone().multiply(restFrame.clone().invert()):torso.clone().multiply(restTorso.clone().invert())).multiply(r.world)).normalize();
   else if(options?.faceDirection&&b.name==='Head'&&options.faceDirection[i][2]>=.5){
    // Head: kept upright between the trunk and vertical, and turned to where the face points in the image (nose against the
    // visible ear). Turned at most 80 degrees from the trunk so a bad face estimate cannot twist the neck.
    const [fx,fy]=options.faceDirection[i],sideways=Math.max(-1,Math.min(1,fx)),down=Math.max(-.6,Math.min(.6,fy-.25)),up=p[8].clone().sub(p[0]).normalize().add(new T.Vector3(0,1,0)).normalize(),face=new T.Vector3(sideways,-down,Math.sqrt(Math.max(0,1-sideways*sideways-down*down))),forward=face.addScaledVector(up,-face.dot(up));
    if(forward.lengthSq()>1e-6){forward.normalize();const target=new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(new T.Vector3().crossVectors(up,forward).normalize(),up,forward)),turn=torso.angleTo(target),head=turn>1.4?torso.clone().slerp(target,1.4/turn):target;q=parent.clone().invert().multiply(head.multiply(restTorso.clone().invert()).multiply(r.world)).normalize();}
   }
   else if(limbMap[b.name]){const [a,c]=limbMap[b.name],direction=p[c].clone().sub(p[a]);
    // After the first frame the limb is carried by its parent's turn since the previous frame and then swung the short way from
    // where it pointed. Swinging from the rest pose each frame flips the limb's roll when it passes opposite its rest direction,
    // for example a leg kicked straight up.
    const before=options?carry.get(b):undefined;
    if(before&&direction.lengthSq()>1e-10){const turn=parent.clone().multiply(before.parent.clone().invert()),world=new T.Quaternion().setFromUnitVectors(before.direction.clone().applyQuaternion(turn).normalize(),direction.clone().normalize()).multiply(turn).multiply(before.world);q=parent.clone().invert().multiply(world).normalize();
     // Carrying alone lets the roll drift over a spin, so it is eased back toward the roll the rest pose implies: 20% a frame when
     // the limb points along its rest direction, fading to nothing when it points opposite (where that roll is undefined).
     const anchored=localForDirection(parent,r.world,r.direction!,direction,restWorlds.get(b.parent!)),along=r.direction!.clone().normalize().applyQuaternion(parent.clone().multiply(restWorlds.get(b.parent!)!.clone().invert())).dot(direction.clone().normalize());q.slerp(anchored,.2*(1+along)/2).normalize();}
    else q=localForDirection(parent,r.world,r.direction!,direction,options?restWorlds.get(b.parent!):undefined);
    // The knee is a hinge: it bends one way and the shin cannot twist against the thigh (textbook: none when straight, about 20
    // degrees when bent). So the shin only swings from where the thigh carries it, and once the knee is bent the thigh is rolled
    // about its own length until that swing is a pure bend, shin behind the front of the thigh. The roll fades in between 10 and
    // 30 degrees of bend, because a straight leg does not say which way its knee faces.
    if(options&&b.name.startsWith('calf_'))q=localForDirection(parent,r.world,r.direction!,direction,restWorlds.get(b.parent!));
    if(options&&b.name.startsWith('thigh_')&&direction.lengthSq()>1e-10){const d=direction.clone().normalize(),shin=p[c+1].clone().sub(p[c]);
     if(shin.lengthSq()>1e-10){shin.normalize();const u=Math.min(1,Math.max(0,(d.angleTo(shin)-.17)/.35)),side=shin.clone().addScaledVector(d,-shin.dot(d)),d0=r.direction!.clone().normalize(),f0=restForward.clone().addScaledVector(d0,-restForward.dot(d0));
      if(u>0&&side.lengthSq()>1e-8&&f0.lengthSq()>1e-8){const f=side.normalize().negate();f0.normalize();const basis=(a:T.Vector3,e:T.Vector3)=>new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(a,e,new T.Vector3().crossVectors(a,e)));q.slerp(parent.clone().invert().multiply(basis(d,f).multiply(basis(d0,f0).invert()).multiply(r.world)).normalize(),u*u*(3-2*u)).normalize();}}}
    if(options)carry.set(b,{parent:parent.clone(),world:parent.clone().multiply(q),direction:direction.clone().normalize()});}
   b.quaternion.copy(q);b.updateWorldMatrix(false,true);
   const prior=tracks![j].keys.at(-1)?.value;if(prior&&q.dot(new T.Quaternion().fromArray(prior))<0)q.set(-q.x,-q.y,-q.z,-q.w);tracks![j].keys.push({time:times[i]-start,value:q.toArray()});
  }
  if(options){const t=times[i]-start,bendAt=(a:number,k:number,e:number)=>p[k].clone().sub(p[a]).angleTo(p[e].clone().sub(p[k]))*deg,inverse=hipFrame.clone().invert();
   note('knee_l bend',150,bendAt(4,5,6),t);note('knee_r bend',150,bendAt(1,2,3),t);note('elbow_l bend',150,bendAt(11,12,13),t);note('elbow_r bend',150,bendAt(14,15,16),t);note('trunk bend',50,p[7].clone().sub(p[0]).angleTo(p[8].clone().sub(p[7]))*deg,t);
   for(const [side,h,k,out] of [['l',4,5,1],['r',1,2,-1]] as const){const v=p[k].clone().sub(p[h]).normalize().applyQuaternion(inverse),flex=Math.atan2(v.z,-v.y)*deg,away=Math.asin(Math.max(-1,Math.min(1,v.x*out)))*deg;/* a thigh past straight up is still flexed, not extended */note(`hip_${side} flexion`,120,flex>-90?flex:flex+360,t);note(`hip_${side} extension`,30,flex>-90?-flex:0,t);note(`hip_${side} abduction`,45,away,t);note(`hip_${side} adduction`,30,-away,t);
    const world=(n:string)=>get(n).getWorldQuaternion(new T.Quaternion()).multiply(restWorlds.get(get(n))!.clone().invert()),thigh=world('thigh_'+side),axis=point('calf_'+side).sub(point('thigh_'+side)).normalize();
    note(`knee_${side} twist`,20,twist(thigh.clone().invert().multiply(world('calf_'+side)),axis.clone().applyQuaternion(thigh.clone().invert())),t);note(`hip_${side} twist`,50,twist(world('pelvis').invert().multiply(thigh),axis.clone().applyQuaternion(thigh.clone().invert())),t);}}
  // Solid body parts, measured on the rig itself (R30): the fit keeps its own skeleton's parts apart, but the character has its
  // own proportions, so this is the check that matches what is seen. Rods with a radius in metres at character scale 1.
  if(options){const P=(n:string)=>point(n).divideScalar(worldScale),gapTo=(q:T.Vector3,a:T.Vector3,b:T.Vector3)=>{const ab=b.clone().sub(a),u=Math.min(1,Math.max(0,q.clone().sub(a).dot(ab)/Math.max(ab.lengthSq(),1e-9)));return q.distanceTo(a.clone().addScaledVector(ab,u));};
   const pelvis=P('pelvis'),neck=P('neck_01'),head=P('Head'),crown=head.clone().add(head.clone().sub(neck).normalize().multiplyScalar(.12)),leg=(s:string)=>[P('thigh_'+s),P('calf_'+s),P('foot_'+s)],arm=(s:string)=>[P('upperarm_'+s),P('lowerarm_'+s),P('hand_'+s)],legs={l:leg('l'),r:leg('r')},arms={l:arm('l'),r:arm('r')};let worst=0,pair='';
   const test=(name:string,q:T.Vector3,r:number,a:T.Vector3,b:T.Vector3,R:number)=>{const inside=r+R-gapTo(q,a,b);if(inside>worst){worst=inside;pair=name;}};
   for(const s of ['l','r'] as const){const [h,k,f]=legs[s],[sh,e,w]=arms[s],o=arms[s==='l'?'r':'l'];
    for(const [n,q,r] of [['knee',k,.06],['shin',k.clone().lerp(f,.5),.055],['ankle',f,.045]] as const){test(`${n}_${s} in trunk`,q,r,pelvis,neck,.13);test(`${n}_${s} in head`,q,r,head,crown,.1);}
    for(const [n,q,r] of [['elbow',e,.04],['forearm',e.clone().lerp(w,.5),.04],['wrist',w,.035]] as const){test(`${n}_${s} in trunk`,q,r,pelvis,neck,.11);test(`${n}_${s} in head`,q,r,head,crown,.1);
     for(const t of ['l','r'] as const){test(`${n}_${s} in thigh_${t}`,q,r,legs[t][0],legs[t][1],.075);test(`${n}_${s} in shin_${t}`,q,r,legs[t][1],legs[t][2],.055);}
     if(s==='r'){test(`${n}_r in upperarm_l`,q,r,o[0],o[1],.045);test(`${n}_r in forearm_l`,q,r,o[1],o[2],.04);}}}
   solid.push({time:times[i]-start,inside:worst,pair});}
  model.updateMatrixWorld(true);const floor=Math.min(point('ball_l').y,point('ball_r').y);const x=(imagePelvis[i][0]-imagePelvis[0][0])*pixelScale;
  // Explicit approximate image-X travel and geometric floor placement, not contact reconstruction.
  rootTrack.keys.push({time:times[i]-start,value:[x,.035-floor,0]});
 });
 // Airborne clips: the lowest foot is no longer assumed to touch the floor. Its height comes from how far the lowest ankle
 // sits above the lowest line it reaches in the clip. Rising onto the toes lifts an ankle by up to about 20 cm without
 // leaving the floor, so the lift fades in between 20 and 40 cm.
 let peakLift=0;if(options?.airborne){const y=options.lowestAnkleImageY;if(!y||y.length!==times.length||y.some(v=>!Number.isFinite(v)))throw Error('Airborne retargeting needs ankle image heights');const ground=[...y].sort((a,b)=>a-b)[Math.floor(y.length*.95)];rootTrack.keys.forEach((k,i)=>{const h=Math.max(0,(ground-y[i])*pixelScale),u=Math.min(1,Math.max(0,(h-.2)/.2)),lift=h*u*u*(3-2*u);peakLift=Math.max(peakLift,lift);(k.value as number[])[1]+=lift;});}
 tracks!.push(rootTrack);const boundaries=[0,.25,1.05,1.33,1.47,1.7,1.95,total],names=['Ready','Gather','Chamber','Lateral snap','Recoil','Return','Ready hold'];
 if(options){const phases=options.phases?.length?options.phases:[{name:'Estimated motion',end:total}];let at=0;phases.forEach((p,i)=>{const end=i===phases.length-1?total:p.end;if(!(end>at+1e-6)||end>total+1e-6)throw Error('Phase ends must ascend within the window');at=end;});if(Math.abs(phases.at(-1)!.end-total)>1e-3)throw Error('Final phase must end at the window duration');at=0;const custom:Action={version:2,rig:'quaternius-ual1',id,name:options.name,phases:phases.map((p,i)=>{const end=i===phases.length-1?total:p.end,phase={id:'video-'+i,name:p.name,intent:'Estimated video motion; support, twist and travel need review',duration:end-at,kind:p.kind||'move',clip:'A_TPose',from:0,to:0};at=end;return phase;}),tracks};validateAction(custom);return {action:custom,metadata:{adapter:'h36m17-quaternius-direction-v1',worldScale,rootTravel:'image-X normalized by initial bounding-box height; no calibrated world Z',floorPlacement:options.airborne?'lowest ball joint on the floor, plus the lowest ankle image height once it exceeds 20-40 cm; assumes a level camera and a subject at constant distance':'lowest ball joint per frame, no confirmed support/contact',peakLiftMeters:peakLift,rigProportions,bodyPartsInside:{thresholdMeters:.02,frames:solid.filter(x=>x.inside>.02).length,worstMeters:Math.round(Math.max(0,...solid.map(x=>x.inside))*1000)/1000,stretches:solid.reduce((runs:{from:number,to:number,worstMeters:number,pair:string}[],x,i)=>{if(x.inside>.02){const last=runs.at(-1);if(last&&i>0&&solid[i-1].inside>.02){last.to=Math.round(x.time*100)/100;if(x.inside>last.worstMeters){last.worstMeters=Math.round(x.inside*1000)/1000;last.pair=x.pair;}}else runs.push({from:Math.round(x.time*100)/100,to:Math.round(x.time*100)/100,worstMeters:Math.round(x.inside*1000)/1000,pair:x.pair});}return runs;},[])},jointRanges:Object.entries(ranges).map(([key,e])=>({joint:key.split(' ')[0],motion:key.split(' ')[1],limitDegrees:e.limit,peakDegrees:Math.round(e.peak),peakTime:Math.round(e.time*100)/100,framesBeyond:e.beyond})),unknown:['twist','foot/finger articulation','calibrated root travel','mirroring'],boneLengths:'rest local translations/scales preserved'}};}
 const action:Action={version:2,rig:'quaternius-ual1',id,name:'Video · Side kick reconstruction draft',phases:names.map((name,i)=>({id:'video-'+i,name,intent:'Estimated video motion; support, twist and travel need review',duration:boundaries[i+1]-boundaries[i],kind:i===3?'fast':i===0||i===6?'hold':'move',clip:'A_TPose',from:0,to:0})),tracks};validateAction(action);
 return {action,metadata:{adapter:'h36m17-quaternius-direction-v1',worldScale,rootTravel:'image-X normalized by initial bounding-box height; no calibrated world Z',floorPlacement:'lowest ball joint per frame, no confirmed support/contact',unknown:['twist','foot/finger articulation','calibrated root travel','mirroring'],boneLengths:'rest local translations/scales preserved'}};
}
