import * as T from 'three/webgpu';
import {Action,validateAction} from '../../runtime/action';
// Specific H36M17 -> Quaternius adapter. No joint positions/scales are authored.
export function bodyFrame(left:T.Vector3,right:T.Vector3,up:T.Vector3){const x=left.clone().sub(right).normalize(),y=up.clone().addScaledVector(x,-up.dot(x)).normalize();if(x.lengthSq()<.9||y.lengthSq()<.9)throw Error('Degenerate body frame');const z=new T.Vector3().crossVectors(x,y).normalize();return new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(x,y,z));}
// Torso frame: the pelvis-to-neck direction is kept exactly and the shoulder line is squared to it. Squaring the spine to
// the shoulders instead would remove any sideways lean whenever the shoulders stay level.
export function torsoFrame(left:T.Vector3,right:T.Vector3,up:T.Vector3){const y=up.clone().normalize(),across=left.clone().sub(right),x=across.addScaledVector(y,-across.dot(y)).normalize();if(y.lengthSq()<.9||x.lengthSq()<.9)throw Error('Degenerate torso frame');const z=new T.Vector3().crossVectors(x,y).normalize();return new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(x,y,z));}
// With parentRestWorld, the limb first turns with its parent (so knees and elbows keep facing the way the body faces through a
// spin) and then swings the shortest way onto the target direction. Without it, the swing starts from the rest pose in world space.
export function localForDirection(parentWorld:T.Quaternion,restWorld:T.Quaternion,restDirection:T.Vector3,direction:T.Vector3,parentRestWorld?:T.Quaternion){if(direction.lengthSq()<1e-10)throw Error('Degenerate limb direction');const carried=parentRestWorld?parentWorld.clone().multiply(parentRestWorld.clone().invert()):new T.Quaternion(),world=new T.Quaternion().setFromUnitVectors(restDirection.clone().normalize().applyQuaternion(carried),direction.clone().normalize()).multiply(carried).multiply(restWorld);return parentWorld.clone().invert().multiply(world).normalize();}
export function retarget(model:T.Object3D,positions:number[][][],times:number[],imagePelvis:number[][],pixelScale:number,id='video-side-kick-draft',options?:{name:string,cameraHip?:number[][],airborne?:boolean,lowestAnkleImageY?:number[],lowestIsBody?:boolean,boneRotations?:{bones:string[],quaternions:number[][][],restDirections:Record<string,number[]|null>,unreliableFrames?:number[]},faceDirection?:number[][],phases?:{name:string,end:number,kind?:'move'|'fast'|'hold'}[]}){
 if(positions.length!==times.length||times.length<2||times.length>256||positions.some(f=>f.length!==17||f.some(p=>p.length!==3||p.some(x=>!Number.isFinite(x)))))throw Error('Invalid estimated motion');
 if(imagePelvis.length!==times.length||imagePelvis.some(p=>p.length!==2||p.some(x=>!Number.isFinite(x)))||!Number.isFinite(pixelScale)||pixelScale<=0)throw Error('Invalid image trajectory');
 const start=times[0],total=times.at(-1)!-start;if(total<=0||times.some((t,i)=>!Number.isFinite(t)||i>0&&t<=times[i-1]))throw Error('Invalid times');
 if(!options&&Math.abs(total-2.3)>1e-6)throw Error('Pilot adapter requires the 2.3-second side-kick window');
 const bones:T.Object3D[]=[];model.traverse(b=>{if((b as T.Bone).isBone)bones.push(b)});const depth=(b:T.Object3D):number=>b.parent?1+depth(b.parent):0;bones.sort((a,b)=>depth(a)-depth(b));model.updateMatrixWorld(true);
 const get=(n:string)=>{const b=model.getObjectByName(n);if(!b)throw Error('Missing bone '+n);return b;},point=(n:string)=>get(n).getWorldPosition(new T.Vector3());
 const restFrame=bodyFrame(point('thigh_l'),point('thigh_r'),point('neck_01').sub(point('pelvis'))),restTorso=options?torsoFrame(point('upperarm_l'),point('upperarm_r'),point('neck_01').sub(point('pelvis'))):restFrame;
 const limbMap:Record<string,[number,number,string]>={thigh_r:[1,2,'calf_r'],calf_r:[2,3,'foot_r'],thigh_l:[4,5,'calf_l'],calf_l:[5,6,'foot_l'],upperarm_l:[11,12,'lowerarm_l'],lowerarm_l:[12,13,'hand_l'],upperarm_r:[14,15,'lowerarm_r'],lowerarm_r:[15,16,'hand_r']};
 const rest=bones.map(b=>({b,q:b.quaternion.clone(),world:b.getWorldQuaternion(new T.Quaternion()),direction:limbMap[b.name]?point(limbMap[b.name][2]).sub(b.getWorldPosition(new T.Vector3())):null}));
 const carry=new Map<T.Object3D,{parent:T.Quaternion,world:T.Quaternion,direction:T.Vector3}>();const restWorlds=new Map<T.Object3D,T.Quaternion>();model.traverse(o=>{restWorlds.set(o,o.getWorldQuaternion(new T.Quaternion()));});const tracks:Action['tracks']=bones.map(b=>({target:b.name,property:'rotation',mode:'absolute',interpolation:'linear',keys:[]}));const rootTrack:NonNullable<Action['tracks']>[number]={target:'$root',property:'position',mode:'absolute',interpolation:'linear',keys:[]};
 const scale=new T.Vector3();model.getWorldScale(scale);const worldScale=scale.x;
 // Rotation path. When the estimate carries the body model's own joint rotations, each mapped bone is turned from its rest pose by
 // the same world rotation the model's joint has turned from the model's rest pose. The two rest poses differ (the model's arms
 // hang lower than our T-pose), so each bone first gets the fixed turn that lays its rest direction on the model's: world =
 // D . A . rest, with A taking our rest direction to the model's. Hands and toes take their forearm's and foot's A; pelvis and
 // head need none. Twist then comes from the model instead of being inferred. Not used when the estimate marks frames whose
 // rotations belong to a reading that was replaced.
 const given=options?.boneRotations,poseReason=!given?undefined:given.quaternions.length!==times.length?'rotation count does not match the samples':given.unreliableFrames?.length?`${given.unreliableFrames.length} frames have rotations from a replaced reading`:undefined;
 const nextBone:Record<string,string>={spine_01:'spine_02',spine_02:'spine_03',spine_03:'neck_01',neck_01:'Head',clavicle_l:'upperarm_l',upperarm_l:'lowerarm_l',lowerarm_l:'hand_l',clavicle_r:'upperarm_r',upperarm_r:'lowerarm_r',lowerarm_r:'hand_r',thigh_l:'calf_l',calf_l:'foot_l',foot_l:'ball_l',thigh_r:'calf_r',calf_r:'foot_r',foot_r:'ball_r',...Object.fromEntries(['l','r'].flatMap(side=>['thumb','index','middle','ring','pinky'].flatMap(f=>[[`${f}_01_${side}`,`${f}_02_${side}`],[`${f}_02_${side}`,`${f}_03_${side}`],[`${f}_03_${side}`,`${f}_04_leaf_${side}`]])))},leans:Record<string,string>={hand_l:'lowerarm_l',hand_r:'lowerarm_r',ball_l:'foot_l',ball_r:'foot_r'};
 const turns=given&&!poseReason?{at:new Map(given.bones.map((n,k)=>[n,k] as [string,number])),frames:given.quaternions,align:new Map(given.bones.map(n=>{const from=leans[n]??n,d=given.restDirections[from],next=nextBone[from];return [n,d&&next?new T.Quaternion().setFromUnitVectors(point(next).sub(point(from)).normalize(),new T.Vector3(d[0],d[1],d[2]).normalize()):new T.Quaternion()] as [string,T.Quaternion];}))}:null;const solid:{time:number,inside:number,pair:string}[]=[];const shake:number[][][]=[],shakeNames=['knee_l','foot_l','knee_r','foot_r','elbow_l','hand_l','elbow_r','hand_r','head'];const crossings:{time:number,pair:string}[]=[],sidesBefore=new Map<string,{over:boolean,front:boolean}>();const span=(a:string,b:string)=>Math.round(point(a).distanceTo(point(b))/worldScale*1000)/1000,rigProportions={hipWidth:span('thigh_l','thigh_r'),shoulderWidth:span('upperarm_l','upperarm_r'),pelvisToNeck:span('pelvis','neck_01'),neckToHead:span('neck_01','Head'),thigh:span('thigh_l','calf_l'),shin:span('calf_l','foot_l'),upperArm:span('upperarm_l','lowerarm_l'),forearm:span('lowerarm_l','hand_l'),hipInPelvisFrame:point('thigh_l').sub(point('pelvis')).divideScalar(worldScale).applyQuaternion(restFrame.clone().invert()).toArray().map(x=>Math.round(x*1000)/1000),neckInTorsoFrame:point('neck_01').sub(point('pelvis')).divideScalar(worldScale).applyQuaternion(restTorso.clone().invert()).toArray().map(x=>Math.round(x*1000)/1000),shoulderInTorsoFrame:point('upperarm_l').sub(point('neck_01')).divideScalar(worldScale).applyQuaternion(restTorso.clone().invert()).toArray().map(x=>Math.round(x*1000)/1000),headInTorsoFrame:point('Head').sub(point('neck_01')).divideScalar(worldScale).applyQuaternion(restTorso.clone().invert()).toArray().map(x=>Math.round(x*1000)/1000),hipBelowPelvis:Math.round((point('pelvis').y-point('thigh_l').y)/worldScale*1000)/1000,shoulderBelowNeck:Math.round((point('neck_01').y-point('upperarm_l').y)/worldScale*1000)/1000};
 // Joint ranges (R27). Textbook adult ranges in degrees; see docs/RULE_LOG.md for sources. Knee and elbow are enforced elsewhere;
 // the rest are only reported, because trained performers pass the hip figures in every split and high kick.
 const restForward=new T.Vector3(0,0,1).applyQuaternion(restFrame),deg=180/Math.PI,ranges:Record<string,{limit:number,peak:number,time:number,beyond:number}>={};
 const note=(key:string,limit:number,value:number,time:number)=>{const e=ranges[key]??={limit,peak:-Infinity,time:0,beyond:0};if(value>e.peak){e.peak=value;e.time=time;}if(value>limit)e.beyond++;};
 const twist=(q:T.Quaternion,axis:T.Vector3)=>{const a=2*Math.atan2(new T.Vector3(q.x,q.y,q.z).dot(axis),q.w)*deg;return Math.abs(((a+540)%360)-180);};
 let armsSwungOut=0,handsLaidFrames=0;
 positions.forEach((frame,i)=>{
  // Camera x-right/y-down/z-away -> Three x-right/y-up/z-toward camera.
  const p=frame.map(v=>new T.Vector3(v[0],-v[1],-v[2]));const hipFrame=bodyFrame(p[4],p[1],p[8].clone().sub(p[0])),torso=options?torsoFrame(p[11],p[14],p[8].clone().sub(p[0])):bodyFrame(p[11],p[14],p[8].clone().sub(p[0]));
  model.position.set(0,0,0);model.updateMatrixWorld(true);
  for(let j=0;j<rest.length;j++){
   const r=rest[j],b=r.b,parent=b.parent!.getWorldQuaternion(new T.Quaternion());let q=r.q.clone();
   if(turns?.at.has(b.name))q=parent.clone().invert().multiply(new T.Quaternion().fromArray(turns.frames[i][turns.at.get(b.name)!]).multiply(turns.align.get(b.name)!).multiply(r.world)).normalize();
   else if(b.name==='pelvis'||['spine_01','spine_02','spine_03'].includes(b.name))q=parent.clone().invert().multiply((b.name==='pelvis'?hipFrame.clone().multiply(restFrame.clone().invert()):torso.clone().multiply(restTorso.clone().invert())).multiply(r.world)).normalize();
   else if(options?.faceDirection&&b.name==='Head'&&options.faceDirection[i][2]>=.5){
    // Head: kept upright between the trunk and vertical, and turned to where the face points in the image (nose against the
    // visible ear). Turned at most 80 degrees from the trunk so a bad face estimate cannot twist the neck.
    const [fx,fy]=options.faceDirection[i],sideways=Math.max(-1,Math.min(1,fx)),down=Math.max(-.6,Math.min(.6,fy-.25)),up=p[8].clone().sub(p[0]).normalize().add(new T.Vector3(0,1,0)).normalize(),face=new T.Vector3(sideways,-down,Math.sqrt(Math.max(0,1-sideways*sideways-down*down))),forward=face.addScaledVector(up,-face.dot(up));
    if(forward.lengthSq()>1e-6){forward.normalize();const target=new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(new T.Vector3().crossVectors(up,forward).normalize(),up,forward)),turn=torso.angleTo(target),head=turn>1.4?torso.clone().slerp(target,1.4/turn):target;q=parent.clone().invert().multiply(head.multiply(restTorso.clone().invert()).multiply(r.world)).normalize();}
   }
   else if(limbMap[b.name]){const [a,c]=limbMap[b.name],direction=p[c].clone().sub(p[a]);
    // After the first frame the limb is carried by its parent's turn since the previous frame and then swung the short way from
    // where it pointed. Swinging from the rest pose each frame flips the limb's roll when it passes opposite its rest direction,
    // for example a leg kicked straight up.
    const before=options?carry.get(b):undefined;
    if(before&&direction.lengthSq()>1e-10){const turn=parent.clone().multiply(before.parent.clone().invert()),world=new T.Quaternion().setFromUnitVectors(before.direction.clone().applyQuaternion(turn).normalize(),direction.clone().normalize()).multiply(turn).multiply(before.world);q=parent.clone().invert().multiply(world).normalize();
     // Carrying alone lets the roll drift over a spin, so it is eased back toward the roll the rest pose implies: 20% a frame when
     // the limb points along its rest direction, fading to nothing when it points opposite (where that roll is undefined).
     const anchored=localForDirection(parent,r.world,r.direction!,direction,restWorlds.get(b.parent!)),along=r.direction!.clone().normalize().applyQuaternion(parent.clone().multiply(restWorlds.get(b.parent!)!.clone().invert())).dot(direction.clone().normalize());q.slerp(anchored,.2*(1+along)/2).normalize();}
    else q=localForDirection(parent,r.world,r.direction!,direction,options?restWorlds.get(b.parent!):undefined);
    // The knee is a hinge: it bends one way and the shin cannot twist against the thigh (textbook: none when straight, about 20
    // degrees when bent). So the shin only swings from where the thigh carries it, and once the knee is bent the thigh is rolled
    // about its own length until that swing is a pure bend, shin behind the front of the thigh. The roll fades in between 10 and
    // 30 degrees of bend, because a straight leg does not say which way its knee faces.
    if(options&&b.name.startsWith('calf_'))q=localForDirection(parent,r.world,r.direction!,direction,restWorlds.get(b.parent!));
    if(options&&b.name.startsWith('thigh_')&&direction.lengthSq()>1e-10){const d=direction.clone().normalize(),shin=p[c+1].clone().sub(p[c]);
     if(shin.lengthSq()>1e-10){shin.normalize();const u=Math.min(1,Math.max(0,(d.angleTo(shin)-.17)/.35)),side=shin.clone().addScaledVector(d,-shin.dot(d)),d0=r.direction!.clone().normalize(),f0=restForward.clone().addScaledVector(d0,-restForward.dot(d0));
      if(u>0&&side.lengthSq()>1e-8&&f0.lengthSq()>1e-8){const f=side.normalize().negate();f0.normalize();const basis=(a:T.Vector3,e:T.Vector3)=>new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(a,e,new T.Vector3().crossVectors(a,e)));q.slerp(parent.clone().invert().multiply(basis(d,f).multiply(basis(d0,f0).invert()).multiply(r.world)).normalize(),u*u*(3-2*u)).normalize();}}}
    if(options)carry.set(b,{parent:parent.clone(),world:parent.clone().multiply(q),direction:direction.clone().normalize()});}
   b.quaternion.copy(q);b.updateWorldMatrix(false,true);
   const prior=tracks![j].keys.at(-1)?.value;if(prior&&q.dot(new T.Quaternion().fromArray(prior))<0)q.set(-q.x,-q.y,-q.z,-q.w);tracks![j].keys.push({time:times[i]-start,value:q.toArray()});
  }
  // Rotation path: an arm inside another body part is swung out at the shoulder. The model's joint angles are right for the
  // model's body; on our character's proportions a hand that brushes the thigh there can land inside it here. The position path
  // did not have this, because it placed limbs by where the joints were. So where the elbow, mid forearm or wrist is inside the
  // trunk, the head, a thigh or a shin (the same rods as the measure below), the upper arm turns about the shoulder by the
  // smallest angle that brings that point to the surface. The turn starts 4 cm before the touch and grows smoothly, so it does not pop in or out.
  if(turns&&options){const S=(n:string)=>point(n).divideScalar(worldScale);let moved=false,laid=false;
   // Then the hand itself: the palm and the fingertips. With the wrist at the surface the hand could still point through the
   // leg (Cheat 720: palm 3 cm from the knee's centre for four frames). The hand turns about the wrist until palm and
   // fingertips lie on the surface, which is a hand touching the leg. The thigh is taken at the mesh's own thickness here
   // (8 cm near the hip, 5.5 cm at the knee, measured on the character), so the hand rests on it and does not hover.
   for(const s of ['l','r'])for(const level of ['arm','hand'] as const){const j=rest.findIndex(r=>r.b.name===(level==='arm'?'upperarm_':'hand_')+s);if(j<0||level==='hand'&&!turns.at.has('middle_01_'+s))continue;const b=rest[j].b;
    for(let pass=0;pass<4;pass++){const sh=S('upperarm_'+s),e=S('lowerarm_'+s),w=S('hand_'+s),pelvis=S('pelvis'),neck=S('neck_01'),head=S('Head'),crown=head.clone().add(head.clone().sub(neck).normalize().multiplyScalar(.12)),pivot=level==='arm'?sh:w;
     const rods:[T.Vector3,T.Vector3,number,number][]=[[pelvis,neck,.11,.11],[head,crown,.1,.1],...(['l','r'].flatMap(t=>[[S('thigh_'+t),S('calf_'+t),level==='arm'?.075:.08,level==='arm'?.075:.055],[S('calf_'+t),S('foot_'+t),.055,.055]]) as [T.Vector3,T.Vector3,number,number][])];let depth=-1,at=w,push=new T.Vector3();const ease=.04;
     for(const [q,r] of (level==='arm'?[[e,.04],[e.clone().lerp(w,.5),.04],[w,.035]]:[[S('middle_01_'+s),.025],[S('middle_04_leaf_'+s),.012]]) as [T.Vector3,number][])for(const [a,c,R0,R1] of rods){const ab=c.clone().sub(a),u=Math.min(1,Math.max(0,q.clone().sub(a).dot(ab)/Math.max(ab.lengthSq(),1e-9))),near=a.clone().addScaledVector(ab,u),gap=q.distanceTo(near),d=r+R0+(R1-R0)*Math.min(1,Math.max(0,2*u-1))-gap;if(d>depth&&gap>1e-6){depth=d;at=q;push=q.clone().sub(near).divideScalar(gap);}}
     if(depth<=(pass?1e-4:-ease))break;/* first pass eases in from 4 cm away, so the turn starts before the touch and reaches the full depth by 4 cm inside */const turnBy=pass||depth>=ease?depth:(depth+ease)*(depth+ease)/(4*ease);const lever=at.clone().sub(pivot),axis=lever.clone().cross(push),reach=axis.length();if(reach<1e-4)break;
     const parent=b.parent!.getWorldQuaternion(new T.Quaternion()),q=parent.clone().invert().multiply(new T.Quaternion().setFromAxisAngle(axis.divideScalar(reach),Math.min(.35,turnBy/reach)).multiply(b.getWorldQuaternion(new T.Quaternion()))).normalize();
     b.quaternion.copy(q);b.updateWorldMatrix(false,true);const keys=tracks![j].keys,prior=keys.at(-2)?.value;if(prior&&q.dot(new T.Quaternion().fromArray(prior))<0)q.set(-q.x,-q.y,-q.z,-q.w);keys[keys.length-1].value=q.toArray();if(depth>0){if(level==='arm')moved=true;else laid=true;}}}
   if(laid)handsLaidFrames++;
   if(moved)armsSwungOut++;}
  if(options){const t=times[i]-start,bendAt=(a:number,k:number,e:number)=>p[k].clone().sub(p[a]).angleTo(p[e].clone().sub(p[k]))*deg,inverse=hipFrame.clone().invert();
   note('knee_l bend',150,bendAt(4,5,6),t);note('knee_r bend',150,bendAt(1,2,3),t);note('elbow_l bend',150,bendAt(11,12,13),t);note('elbow_r bend',150,bendAt(14,15,16),t);note('trunk bend',50,p[7].clone().sub(p[0]).angleTo(p[8].clone().sub(p[7]))*deg,t);
   for(const [side,h,k,out] of [['l',4,5,1],['r',1,2,-1]] as const){const v=p[k].clone().sub(p[h]).normalize().applyQuaternion(inverse),flex=Math.atan2(v.z,-v.y)*deg,away=Math.asin(Math.max(-1,Math.min(1,v.x*out)))*deg;/* a thigh past straight up is still flexed, not extended */note(`hip_${side} flexion`,120,flex>-90?flex:flex+360,t);note(`hip_${side} extension`,30,flex>-90?-flex:0,t);note(`hip_${side} abduction`,45,away,t);note(`hip_${side} adduction`,30,-away,t);
    const world=(n:string)=>get(n).getWorldQuaternion(new T.Quaternion()).multiply(restWorlds.get(get(n))!.clone().invert()),thigh=world('thigh_'+side),axis=point('calf_'+side).sub(point('thigh_'+side)).normalize();
    note(`knee_${side} twist`,20,twist(thigh.clone().invert().multiply(world('calf_'+side)),axis.clone().applyQuaternion(thigh.clone().invert())),t);note(`hip_${side} twist`,50,twist(world('pelvis').invert().multiply(thigh),axis.clone().applyQuaternion(thigh.clone().invert())),t);}}
  // Solid body parts, measured on the rig itself (R30): the fit keeps its own skeleton's parts apart, but the character has its
  // own proportions, so this is the check that matches what is seen. Rods with a radius in metres at character scale 1.
  if(options){const P=(n:string)=>point(n).divideScalar(worldScale),gapTo=(q:T.Vector3,a:T.Vector3,b:T.Vector3)=>{const ab=b.clone().sub(a),u=Math.min(1,Math.max(0,q.clone().sub(a).dot(ab)/Math.max(ab.lengthSq(),1e-9)));return q.distanceTo(a.clone().addScaledVector(ab,u));};
   const pelvis=P('pelvis'),neck=P('neck_01'),head=P('Head'),crown=head.clone().add(head.clone().sub(neck).normalize().multiplyScalar(.12)),leg=(s:string)=>[P('thigh_'+s),P('calf_'+s),P('foot_'+s)],arm=(s:string)=>[P('upperarm_'+s),P('lowerarm_'+s),P('hand_'+s)],legs={l:leg('l'),r:leg('r')},arms={l:arm('l'),r:arm('r')};let worst=0,pair='';
   const test=(name:string,q:T.Vector3,r:number,a:T.Vector3,b:T.Vector3,R:number)=>{const inside=r+R-gapTo(q,a,b);if(inside>worst){worst=inside;pair=name;}
    // Across time: a point that overlaps a rod as the camera sees it, in this frame and the last, and has changed from in front
    // of it to behind it (or back) went through it. Leaving the outline first and coming back on the other side is going round.
    const ab=b.clone().sub(a),u=Math.min(1,Math.max(0,q.clone().sub(a).dot(ab)/Math.max(ab.lengthSq(),1e-9))),near=a.clone().addScaledVector(ab,u),over=Math.hypot(q.x-near.x,q.y-near.y)<r+R,front=q.z>near.z,was=sidesBefore.get(name);if(over&&was?.over&&was.front!==front)crossings.push({time:Math.round((times[i]-start)*100)/100,pair:name.replace(' in ',' through ')});sidesBefore.set(name,{over,front});};
   for(const s of ['l','r'] as const){const [h,k,f]=legs[s],[sh,e,w]=arms[s],o=arms[s==='l'?'r':'l'];
    for(const [n,q,r] of [['knee',k,.06],['shin',k.clone().lerp(f,.5),.055],['ankle',f,.045]] as const){test(`${n}_${s} in trunk`,q,r,pelvis,neck,n==='knee'?.1:.13);test(`${n}_${s} in head`,q,r,head,crown,.1);}
    for(const [n,q,r] of [['elbow',e,.04],['forearm',e.clone().lerp(w,.5),.04],['wrist',w,.035]] as const){test(`${n}_${s} in trunk`,q,r,pelvis,neck,.11);test(`${n}_${s} in head`,q,r,head,crown,.1);
     for(const t of ['l','r'] as const){test(`${n}_${s} in thigh_${t}`,q,r,legs[t][0],legs[t][1],.075);test(`${n}_${s} in shin_${t}`,q,r,legs[t][1],legs[t][2],.055);}
     if(s==='r'){test(`${n}_r in upperarm_l`,q,r,o[0],o[1],.045);test(`${n}_r in forearm_l`,q,r,o[1],o[2],.04);}}}
   solid.push({time:times[i]-start,inside:worst,pair});shake.push([legs.l[1],legs.l[2],legs.r[1],legs.r[2],arms.l[1],arms.l[2],arms.r[1],arms.r[2],head].map(q=>q.clone().sub(pelvis).toArray()));}
  // The floor is under whatever is lowest: a foot, or a hand, the head, a knee, an elbow or the hips in a hand-supported,
  // inverted or tucked move. With feet only,
  // a character standing on one hand was hung from its raised feet and sank through the floor.
  model.updateMatrixWorld(true);const floor=options?Math.min(...['ball_l','ball_r','foot_l','foot_r','hand_l','hand_r','Head','pelvis','calf_l','calf_r','lowerarm_l','lowerarm_r'].map(n=>point(n).y)):Math.min(point('ball_l').y,point('ball_r').y);const x=(imagePelvis[i][0]-imagePelvis[0][0])*pixelScale;
  // Explicit approximate image-X travel and geometric floor placement, not contact reconstruction.
  // Scene travel (two performers): sideways and depth travel come from the hips' position in the camera's space, in metres,
   // from this performer's own first frame. Both performers of a window then move in one space, and the constant offset
   // between their first frames (metadata.scene) is all that is needed to stand them together. z is toward the camera.
   const hip=options?.cameraHip;rootTrack.keys.push({time:times[i]-start,value:hip?[hip[i][0]-hip[0][0],.035-floor,-(hip[i][2]-hip[0][2])]:[x,.035-floor,0]});
 });
 // Airborne clips: the lowest foot is no longer assumed to touch the floor. Its height comes from how far the lowest ankle
 // sits above the lowest line it reaches in the clip. Rising onto the toes lifts an ankle by up to about 20 cm without
 // leaving the floor, so the lift fades in between 20 and 40 cm.
 // Jitter: how far each of nine points (knees, feet, elbows, hands, head, relative to the hips) sits from a smooth curve through
 // its five-frame neighbourhood (a quadratic fit). Smooth movement, however fast, leaves almost nothing; frame-to-frame shake
 // shows as millimetres. This is the number smoothing is judged by.
 const off:{mm:number,joint:string,time:number}[]=[];for(let i=2;i<shake.length-2;i++)shake[i].forEach((q,j)=>{const fit=[0,1,2].map(c=>(-3*shake[i-2][j][c]+12*shake[i-1][j][c]+17*q[c]+12*shake[i+1][j][c]-3*shake[i+2][j][c])/35);off.push({mm:Math.hypot(q[0]-fit[0],q[1]-fit[1],q[2]-fit[2])*1000,joint:shakeNames[j],time:Math.round((times[i]-start)*100)/100});});
 const sorted=off.map(x=>x.mm).sort((a,b)=>a-b),worstShake=off.reduce((a,b)=>b.mm>a.mm?b:a,{mm:0,joint:'',time:0}),jitter=off.length?{rmsMillimeters:Math.round(Math.sqrt(off.reduce((sum,x)=>sum+x.mm*x.mm,0)/off.length)*10)/10,p95Millimeters:Math.round(sorted[Math.floor(sorted.length*.95)]*10)/10,worst:{joint:worstShake.joint,time:worstShake.time,millimeters:Math.round(worstShake.mm)}}:null;
 // When the heights come from the body model's own lowest keypoint (toes, heels, hands and head included) rising onto the toes
 // does not lift that point, so the lift follows the height from 2-6 cm up instead of fading in over 20-40 cm; that fade doubled
 // the take-off speed and showed as a jolt.
 let peakLift=0;if(options?.airborne){const y=options.lowestAnkleImageY;if(!y||y.length!==times.length||y.some(v=>!Number.isFinite(v)))throw Error('Airborne retargeting needs ankle image heights');const ground=[...y].sort((a,b)=>a-b)[Math.floor(y.length*.95)];rootTrack.keys.forEach((k,i)=>{const h=Math.max(0,(ground-y[i])*pixelScale),u=options.lowestIsBody?Math.min(1,Math.max(0,(h-.02)/.04)):Math.min(1,Math.max(0,(h-.2)/.2)),lift=h*u*u*(3-2*u);peakLift=Math.max(peakLift,lift);(k.value as number[])[1]+=lift;});}
 tracks!.push(rootTrack);const boundaries=[0,.25,1.05,1.33,1.47,1.7,1.95,total],names=['Ready','Gather','Chamber','Lateral snap','Recoil','Return','Ready hold'];
 if(options){const phases=options.phases?.length?options.phases:[{name:'Estimated motion',end:total}];let at=0;phases.forEach((p,i)=>{const end=i===phases.length-1?total:p.end;if(!(end>at+1e-6)||end>total+1e-6)throw Error('Phase ends must ascend within the window');at=end;});if(Math.abs(phases.at(-1)!.end-total)>1e-3)throw Error('Final phase must end at the window duration');at=0;const custom:Action={version:2,rig:'quaternius-ual1',id,name:options.name,phases:phases.map((p,i)=>{const end=i===phases.length-1?total:p.end,phase={id:'video-'+i,name:p.name,intent:'Estimated video motion; support, twist and travel need review',duration:end-at,kind:p.kind||'move',clip:'A_TPose',from:0,to:0};at=end;return phase;}),tracks};validateAction(custom);return {action:custom,metadata:{adapter:'h36m17-quaternius-direction-v1',worldScale,...(options?.cameraHip?{scene:{space:'camera of the source window: x right, z toward the camera, metres',firstFrameHip:[Math.round(options.cameraHip[0][0]*1000)/1000,Math.round(-options.cameraHip[0][2]*1000)/1000],depthTravelMeters:Math.round((Math.max(...options.cameraHip.map(h=>h[2]))-Math.min(...options.cameraHip.map(h=>h[2])))*1000)/1000}}:{}),rootTravel:options?.cameraHip?'hips in the camera space of the body model, metres, from the first frame; depth is a single-camera estimate':'image-X normalized by initial bounding-box height; no calibrated world Z',floorPlacement:options.airborne?'lowest of ball joints, hands and head on the floor, plus the lowest ankle-or-wrist image height once it exceeds 20-40 cm; assumes a level camera and a subject at constant distance':'lowest of ball joints, hands and head per frame, no confirmed support/contact',peakLiftMeters:peakLift,pose:{requested:given?'rotations':'positions',used:turns?'rotations':'positions',...(poseReason?{reason:poseReason}:{}),...(turns?{armsSwungOutFrames:armsSwungOut,handsLaidOnSurfaceFrames:handsLaidFrames}:{})},jitter,rigProportions,bodyPartsInside:{crossings,thresholdMeters:.02,frames:solid.filter(x=>x.inside>.02).length,worstMeters:Math.round(Math.max(0,...solid.map(x=>x.inside))*1000)/1000,stretches:solid.reduce((runs:{from:number,to:number,worstMeters:number,pair:string}[],x,i)=>{if(x.inside>.02){const last=runs.at(-1);if(last&&i>0&&solid[i-1].inside>.02){last.to=Math.round(x.time*100)/100;if(x.inside>last.worstMeters){last.worstMeters=Math.round(x.inside*1000)/1000;last.pair=x.pair;}}else runs.push({from:Math.round(x.time*100)/100,to:Math.round(x.time*100)/100,worstMeters:Math.round(x.inside*1000)/1000,pair:x.pair});}return runs;},[])},jointRanges:Object.entries(ranges).map(([key,e])=>({joint:key.split(' ')[0],motion:key.split(' ')[1],limitDegrees:e.limit,peakDegrees:Math.round(e.peak),peakTime:Math.round(e.time*100)/100,framesBeyond:e.beyond})),unknown:['twist','foot/finger articulation','calibrated root travel','mirroring'],boneLengths:'rest local translations/scales preserved'}};}
 const action:Action={version:2,rig:'quaternius-ual1',id,name:'Video · Side kick reconstruction draft',phases:names.map((name,i)=>({id:'video-'+i,name,intent:'Estimated video motion; support, twist and travel need review',duration:boundaries[i+1]-boundaries[i],kind:i===3?'fast':i===0||i===6?'hold':'move',clip:'A_TPose',from:0,to:0})),tracks};validateAction(action);
 return {action,metadata:{adapter:'h36m17-quaternius-direction-v1',worldScale,...(options?.cameraHip?{scene:{space:'camera of the source window: x right, z toward the camera, metres',firstFrameHip:[Math.round(options.cameraHip[0][0]*1000)/1000,Math.round(-options.cameraHip[0][2]*1000)/1000],depthTravelMeters:Math.round((Math.max(...options.cameraHip.map(h=>h[2]))-Math.min(...options.cameraHip.map(h=>h[2])))*1000)/1000}}:{}),rootTravel:options?.cameraHip?'hips in the camera space of the body model, metres, from the first frame; depth is a single-camera estimate':'image-X normalized by initial bounding-box height; no calibrated world Z',floorPlacement:'lowest of ball joints, hands and head per frame, no confirmed support/contact',unknown:['twist','foot/finger articulation','calibrated root travel','mirroring'],boneLengths:'rest local translations/scales preserved'}};
}
