import {test} from 'node:test';import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Studio} from '../authoring/core.js';
// Bundle the runtime module for isolated numerical tests without a second project loader.
import {buildSync} from 'esbuild';
const dir=mkdtempSync(join(tmpdir(),'motion-test-module-'));buildSync({entryPoints:['runtime/common-motion.ts'],bundle:true,platform:'node',format:'esm',outfile:join(dir,'motion.mjs')});
const {compareMotion}=await import(join(dir,'motion.mjs'));rmSync(dir,{recursive:true,force:true});
function signature(seconds,angle,rootSpeed=0){const times=Array.from({length:Math.round(seconds*30)+1},(_,i)=>i/30);return {duration:seconds,times,roots:times.map(t=>[0,0,t*rootSpeed]),poses:times.map(t=>{const a=angle(t),v=new Float64Array(105);for(let j=0;j<15;j++){v[j*7]=Math.sin(a)*.2;v[j*7+1]=j/20;v[j*7+3]=Math.sin(a/2);v[j*7+6]=Math.cos(a/2);}return v;})};}
test('finds shared moving window and reports independent root travel',()=>{const a=signature(1,t=>t),b=signature(2,t=>t>=.4&&t<=1.4?t-.4:3,2);const r=compareMotion(a,b,{minDuration:.3,positionTolerance:.005,rotationTolerance:1});assert.ok(r.matches.length);const m=r.matches[0];assert.ok(Math.abs(m.a.start)<1e-8);assert.ok(Math.abs(m.b.start-.4)<1e-8);assert.ok(m.duration>.99);assert.ok(m.positionRmsMeters<1e-8);assert.ok(m.rotationRmsDegrees<1e-5);assert.deepEqual(m.a.rootDisplacement,[0,0,0]);assert.ok(m.b.rootDisplacement[2]>1.99);});
test('holds are excluded by default and explicitly discoverable',()=>{const a=signature(1,()=>0);assert.equal(compareMotion(a,a).matches.length,0);assert.ok(compareMotion(a,a).holdRunsExcluded>0);assert.equal(compareMotion(signature(.5,t=>t*.3),signature(.5,()=>0)).matches.length,0);assert.equal(compareMotion(a,a,{includeHolds:true}).matches[0].classification,'shared-hold');assert.throws(()=>compareMotion(a,a,{minDuration:0}),/Invalid/);});
test('upper-body matching does not claim a whole-body shared motion',()=>{const a=signature(1,t=>t),b=signature(1,t=>t);for(const p of b.poses)for(let j=9;j<15;j++){p[j*7+3]=Math.sin(1);p[j*7+6]=Math.cos(1);}assert.equal(compareMotion(a,b).matches.length,0);assert.ok(compareMotion(a,b,{bodyPart:'upper'}).matches.length);assert.equal(compareMotion(a,b,{bodyPart:'upper'}).joints.length,9);});
test('live-rig source comparison is cached, revision-checked and read-only',async()=>{const d=mkdtempSync(join(tmpdir(),'studio-common-'));try{const s=new Studio(process.cwd(),join(d,'project.json')),library=JSON.parse(readFileSync('runtime/ual2-library.json'));for(const id of ['move-ual2-sword-regular-a','move-ual2-sword-regular-combo']){const m=library.movements.find(m=>m.action.id===id);s.state.actions[id]={category:'movement',revision:1,action:m.action,reference:m.action,metadata:m.metadata,history:[]};}const sequence=s.state.sequence,args={movementA:'move-ual2-sword-regular-a',revisionA:1,movementB:'move-ual2-sword-regular-combo',revisionB:1};const first=await s.call('find_common_motion',args);assert.equal(first.sampledMovements,2);assert.ok(first.matches[0].duration>=.3);assert.ok(Math.abs(first.matches[0].b.end-13/30)<1e-8);assert.equal(first.matches[0].a.bodyDisplacement.length,3);const second=await s.call('find_common_motion',args);assert.equal(second.sampledMovements,0);assert.deepEqual(first.matches,second.matches);const cachedA=s.motionSignatures.get(first.sources[0].motionHash);s.motionSignatures.clear();s.motionSignatures.set(first.sources[0].motionHash,cachedA);for(let i=0;i<5;i++)s.motionSignatures.set('dummy-'+i,cachedA);const afterEviction=await s.call('find_common_motion',args);assert.equal(afterEviction.sampledMovements,1);assert.deepEqual(afterEviction.matches,first.matches);assert.equal(s.motionSignatures.size,6);assert.equal(sequence,s.state.sequence);await assert.rejects(s.call('find_common_motion',{...args,revisionA:2}),/Stale/);await assert.rejects(s.call('find_common_motion',{...args,positionTolerance:9}),/Invalid/);}finally{rmSync(d,{recursive:true,force:true});}});
