import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,readFileSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {buildSync} from 'esbuild';import * as T from 'three/webgpu';import {Studio} from '../authoring/core.js';import {validateContractData,resolveSpec} from '../authoring/contracts.mjs';
const d=mkdtempSync(join(tmpdir(),'connection-module-'));buildSync({entryPoints:['runtime/connection.ts'],bundle:true,platform:'node',format:'esm',packages:'external',outfile:join(d,'connection.mjs')});writeFileSync(join(d,'connection.mjs'),readFileSync(join(d,'connection.mjs'),'utf8').replaceAll('"three/webgpu"',JSON.stringify(new URL('../node_modules/three/build/three.webgpu.js',import.meta.url).href)));const {hermite,rotationBridge}=await import(join(d,'connection.mjs'));rmSync(d,{recursive:true,force:true});
test('position and quaternion bridges preserve endpoint velocity without changing endpoints',()=>{
 const a=new T.Vector3(0,0,0),b=new T.Vector3(.2,0,0),v=new T.Vector3(1,0,0),dt=.2,eps=1e-5;
 assert.ok(hermite(a,b,v,v,0,dt).distanceTo(a)<1e-10);assert.ok(hermite(a,b,v,v,1,dt).distanceTo(b)<1e-10);
 assert.ok(Math.abs(hermite(a,b,v,v,eps,dt).x/(eps*dt)-1)<1e-6);assert.ok(Math.abs((b.x-hermite(a,b,v,v,1-eps,dt).x)/(eps*dt)-1)<1e-6);
 const q=t=>new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),t),f=t=>rotationBridge(q(.3),q(.5),q(.3-1/60),q(.5+1/60),t,dt,1/60,1/60);
 assert.ok(f(0).angleTo(q(.3))<1e-7);assert.ok(f(1).angleTo(q(.5))<1e-7);assert.ok(Math.abs(q(.3).angleTo(f(eps))/(eps*dt)-1)<.001);assert.ok(Math.abs(f(1-eps).angleTo(q(.5))/(eps*dt)-1)<.001);
 const opposite=q(.5);opposite.set(-opposite.x,-opposite.y,-opposite.z,-opposite.w);assert.ok(rotationBridge(q(.3),opposite,q(.3-1/60),q(.5+1/60),.5,dt,1/60,1/60).angleTo(f(.5))<1e-7);
});
test('explicit continued travel carries incoming motion forward, preserves sources and roundtrips recipes',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'connection-studio-'));try{const s=new Studio(process.cwd(),join(dir,'project.json'));const base=structuredClone(s.pair('move-guard').action);base.phases[0].duration=1;base.tracks=base.tracks.filter(t=>t.target!=='$root');base.tracks.push({target:'$root',property:'position',mode:'absolute',interpolation:'linear',keys:[{time:0,value:[0,0,0]},{time:1,value:[0,0,1]}]});const metadata={source:'Test linear travel',support:'unknown',travel:'source',notes:'Synthetic known constant velocity'};
 for(const id of ['move-linear-a','move-linear-b'])await s.call('register_movement',{action:{...base,id},metadata,expectedRevision:0});
 const before=JSON.stringify(s.pair('move-linear-b').action),steps=[{movementId:'move-linear-a',revision:1,speed:1,transition:0},{movementId:'move-linear-b',revision:1,speed:1,transition:.2,blend:'velocity',travel:'continue'}];
 const r=await s.call('compose_action',{actionId:'continuous-test',name:'Continuous test',expectedRevision:0,steps});assert.equal(r.recipe.compiler,'pose-blend-v2');const track=s.pair('continuous-test').action.tracks.find(t=>t.target==='$root'&&t.property==='position');assert.ok(Math.abs(track.keys.at(-1).value[2]-2.2)<1e-6);assert.ok(track.keys.every((k,i)=>!i||k.value[2]>=track.keys[i-1].value[2]-1e-6));assert.equal(JSON.stringify(s.pair('move-linear-b').action),before);
 const quality=await s.call('inspect_motion_quality',{actionId:'continuous-test',sourceRevision:r.revision});assert.ok(quality.seams.every(x=>x.rootVelocityJumpMetersPerSecond<1e-5));
 const exported=await s.call('export_project',{});const second=new Studio(process.cwd(),join(dir,'second.json'));await second.call('import_project',{project:exported,expectedSequence:second.state.sequence});assert.equal(second.pair('continuous-test').recipe.steps[1].blend,'velocity');
 await assert.rejects(s.call('compose_action',{actionId:'invalid-anchor',name:'Invalid anchor',expectedRevision:0,steps:[steps[0],{...steps[1],contact:'left'}]}),/anchoring/);assert.equal(s.state.actions['invalid-anchor'],undefined);
 // Facing continuation: the same movement stored a quarter turn to the left comes in turned back, and its travel turns with it.
 const h=Math.SQRT1_2;await s.call('register_movement',{action:{...base,id:'move-linear-turned',tracks:[...base.tracks,{target:'$root',property:'rotation',mode:'absolute',interpolation:'linear',keys:[{time:0,value:[0,h,0,h]}]}]},metadata,expectedRevision:0});
 await s.call('profile_movement_library',{expectedSequence:s.state.sequence});
 const faced=await s.call('compose_action',{actionId:'facing-test',name:'Facing test',expectedRevision:0,steps:[steps[0],{movementId:'move-linear-turned',revision:1,speed:1,transition:.2,blend:'velocity',travel:'continue',facing:'continue'}]});assert.equal(faced.recipe.steps[1].facing,'continue');
 const at=(property)=>s.pair('facing-test').action.tracks.find(t=>t.target==='$root'&&t.property===property).keys.at(-1).value,end=at('position'),turn=at('rotation');assert.ok(Math.abs(end[0]+1.1)<1e-4&&Math.abs(end[1])<1e-6&&Math.abs(end[2]-1.1)<1e-4,String(end));assert.ok(Math.abs(Math.abs(turn[3])-1)<1e-6,String(turn));
 const unfaced=await s.call('compose_action',{actionId:'unfaced-test',name:'Unfaced test',expectedRevision:0,steps:[steps[0],{movementId:'move-linear-turned',revision:1,speed:1,transition:.2,blend:'velocity',travel:'continue'}]});assert.ok(Math.abs(s.pair('unfaced-test').action.tracks.find(t=>t.target==='$root'&&t.property==='rotation').keys.at(-1).value[1]-h)<1e-6);assert.equal(unfaced.recipe.steps[1].facing,undefined);
 const ranked=x=>(x.find(m=>m.movementId==='move-linear-turned'));const plain=ranked(await s.call('find_movement_connections',{movementId:'move-linear-a',sourceRevision:1,limit:20})),aligned=ranked(await s.call('find_movement_connections',{movementId:'move-linear-a',sourceRevision:1,limit:20,facing:'continue'}));assert.ok(plain&&aligned,'profiles present');assert.ok(plain.poseRmsMeters>.1&&aligned.poseRmsMeters<1e-6&&Math.abs(Math.abs(aligned.turnDegrees)-90)<1e-3&&aligned.rotationRmsDegrees<1e-3,JSON.stringify([plain.poseRmsMeters,aligned]));
 // Facing by travel: this movement already travels the way the previous one went, so it is not turned, whatever its hips say.
 await s.call('compose_action',{actionId:'travel-facing-test',name:'Travel facing test',expectedRevision:0,steps:[steps[0],{movementId:'move-linear-turned',revision:1,speed:1,transition:.2,blend:'velocity',travel:'continue',facing:'travel'}]});const along=p=>s.pair('travel-facing-test').action.tracks.find(t=>t.target==='$root'&&t.property===p).keys.at(-1).value;assert.ok(Math.abs(along('position')[2]-2.2)<1e-4&&Math.abs(along('position')[0])<1e-4,String(along('position')));assert.ok(Math.abs(along('rotation')[1]-h)<1e-6);
 await assert.rejects(s.call('compose_action',{actionId:'invalid-facing',name:'Invalid facing',expectedRevision:0,steps:[steps[0],{movementId:'move-linear-b',revision:1,speed:1,transition:.2,contact:'left',facing:'continue'}]}),/anchoring/);
 }finally{rmSync(dir,{recursive:true,force:true});}
});
test('typed build receipts identify connection modes and existing pose policies cannot approve velocity mode',()=>{
 const dir=mkdtempSync(join(tmpdir(),'connection-spec-'));try{const s=new Studio(process.cwd(),join(dir,'project.json')),spec={schemaVersion:1,rig:'quaternius-ual1',id:'mode-test',name:'Mode test',intent:'Velocity test',steps:[{movementId:'move-guard',revision:1,speed:1},{movementId:'move-kick',revision:1,speed:1,connection:{contractId:'kick-entry',duration:.06,blend:'velocity'}}]};const checked=resolveSpec(s.state,spec,0,false);assert.equal(checked.valid,true);assert.equal(checked.receipt.compiler,'pose-blend-v2');assert.deepEqual(validateContractData(checked.receipt,'receipt'),[]);
 const reviews={seams:[{contractId:'kick-entry',fromRevision:1,toRevision:1,fromHash:checked.receipt.sources[0].motionHash,toHash:checked.receipt.sources[1].motionHash,decision:'supported',reviewRevision:1,configuration:{duration:.06,fromSpeed:1,toSpeed:1,anchor:'none'}}]};assert.equal(resolveSpec(s.state,spec,0,false,reviews).valid,false);
 }finally{rmSync(dir,{recursive:true,force:true});}
});
