import test from 'node:test';
import assert from 'node:assert/strict';
import {WatchState} from '../watch/state.js';
function fixture(){let wall=new Date(2026,9,3,23,59,58).getTime(), mono=100;return {state:new WatchState({now:()=>wall,tick:()=>mono}),advance(ms){wall+=ms;mono+=ms;},jump(ms){wall+=ms;}};}
test('live clock crosses midnight and retains a custom offset',()=>{const f=fixture();f.state.offset=60000;assert.equal(f.state.date().getDate(),4);assert.equal(f.state.date().getMinutes(),0);f.advance(3000);assert.equal(f.state.date().getSeconds(),1);});
test('editing freezes time, wraps hours and minutes, and commits relative to current device time',()=>{const f=fixture(),s=f.state;s.adjust();f.advance(90000);assert.equal(s.date().getMinutes(),59);s.adjust();assert.equal(s.date().getHours(),0);s.modeButton();s.adjust();assert.equal(s.date().getMinutes(),0);s.save();assert.equal(s.edit,null);assert.equal(s.date().getSeconds(),0);f.advance(5000);assert.equal(s.date().getSeconds(),5);});
test('sync exits settings and discards the offset',()=>{const f=fixture(),s=f.state;s.offset=123456;s.adjust();s.sync();assert.equal(s.edit,null);assert.equal(s.offset,0);assert.equal(s.date().getHours(),23);});
test('stopwatch uses monotonic time, pauses, resumes, and survives mode changes',()=>{const f=fixture(),s=f.state;s.modeButton();s.adjust();f.advance(2500);f.jump(86400000);assert.equal(s.stopwatch(),2500);s.adjust();f.advance(5000);assert.equal(s.stopwatch(),2500);s.adjust();s.modeButton();f.advance(1000);assert.equal(s.stopwatch(),3500);s.modeButton();s.resetStopwatch();assert.equal(s.stopwatch(),0);assert.equal(s.started,null);});
test('preferences persist without storing stopwatch or transient settings',()=>{const f=fixture(),s=f.state;s.offset=12345;s.format24=false;s.light();s.adjust();const restored=new WatchState({...s.snapshot()});assert.equal(restored.offset,12345);assert.equal(restored.format24,false);assert.equal(restored.edit,null);assert.equal(restored.lit,false);});
test('asset has editable face and exactly three buttons, valid indices, and complete dependencies',async()=>{const fs=await import('node:fs/promises');const j=JSON.parse(await fs.readFile(new URL('../watch/assets/watch-interactive.gltf',import.meta.url)));assert.equal(j.nodes.filter(n=>n.name.startsWith('button_')).length,3);assert.ok(j.nodes.some(n=>n.name==='custom_face'));const b=await fs.readFile(new URL('../watch/assets/watch-interactive.bin',import.meta.url));for(const m of j.meshes)for(const p of m.primitives){const a=j.accessors[p.indices],v=j.bufferViews[a.bufferView],start=(v.byteOffset||0)+(a.byteOffset||0);for(let i=0;i<a.count;i++)assert.ok(b.readUInt16LE(start+i*2)<j.accessors[p.attributes.POSITION].count);}for(const image of j.images)await fs.access(new URL('../watch/assets/'+image.uri,import.meta.url));});
test('Blender GLB is self-contained and preserves the face and action names',async()=>{const fs=await import('node:fs/promises');const b=await fs.readFile(new URL('../watch/assets/watch.glb',import.meta.url));assert.equal(b.toString('ascii',0,4),'glTF');assert.equal(b.readUInt32LE(4),2);assert.equal(b.readUInt32LE(8),b.length);const n=b.readUInt32LE(12);const j=JSON.parse(b.toString('utf8',20,20+n));assert.equal(j.nodes.filter(n=>n.name.startsWith('button_')).length,3);assert.ok(j.nodes.some(n=>n.name==='custom_face'));assert.ok(j.images.every(i=>i.bufferView!==undefined&&!i.uri));assert.ok(j.buffers.every(b=>!b.uri));});
