import * as T from 'three/webgpu';
import {Action,duration} from './action';
import {CharacterPlayer} from './player';
export const commonJoints=['pelvis','spine_03','Head','upperarm_l','lowerarm_l','hand_l','upperarm_r','lowerarm_r','hand_r','thigh_l','calf_l','foot_l','thigh_r','calf_r','foot_r'];
export type MotionSignature={duration:number;times:number[];poses:Float64Array[];roots:number[][];bodies?:number[][]};
export function sampleSignature(player:CharacterPlayer,action:Action):MotionSignature{
 const total=duration(action),times=Array.from({length:Math.floor(total*30+1e-6)+1},(_,i)=>Math.min(i/30,total));if(Math.abs(times[times.length-1]-total)<1e-6)times[times.length-1]=total;
 const bones=commonJoints.map(n=>player.model.getObjectByName(n)!);if(bones.some(n=>!n))throw Error('Unsupported comparison rig');
 const poses:Float64Array[]=[],roots:number[][]=[],bodies:number[][]=[];
 for(const t of times){player.sample(action,t);const origin=bones[0].getWorldPosition(new T.Vector3());bodies.push(origin.toArray());roots.push(player.model.getWorldPosition(new T.Vector3()).toArray());const p=new Float64Array(bones.length*7);bones.forEach((b,j)=>{p.set(b.getWorldPosition(new T.Vector3()).sub(origin).toArray(),j*7);p.set(b.quaternion.toArray(),j*7+3);});poses.push(p);}
 return {duration:total,times,poses,roots,bodies};
}
export function compareMotion(a:MotionSignature,b:MotionSignature,options:any={}){
 const group=options.bodyPart??'full',min=options.minDuration??.2,posLimit=options.positionTolerance??.06,rotLimit=options.rotationTolerance??12,limit=options.limit??5,includeHolds=options.includeHolds??false;
 if(!['full','upper','lower'].includes(group)||!Number.isFinite(min)||min<.1||min>10||!Number.isFinite(posLimit)||posLimit<.001||posLimit>.25||!Number.isFinite(rotLimit)||rotLimit<.1||rotLimit>45||!Number.isInteger(limit)||limit<1||limit>10||typeof includeHolds!=='boolean')throw Error('Invalid common-motion comparison options');
 const indices=commonJoints.map((_,i)=>i).filter(i=>group==='full'||group==='upper'&&i<9||group==='lower'&&(i===0||i>=9));const rad=rotLimit*Math.PI/180;
 const difference=(x:Float64Array,y:Float64Array,early=false)=>{let p=0,r=0;for(const j of indices){const k=j*7;for(let c=0;c<3;c++)p+=(x[k+c]-y[k+c])**2;const dot=Math.min(1,Math.abs(x[k+3]*y[k+3]+x[k+4]*y[k+4]+x[k+5]*y[k+5]+x[k+6]*y[k+6]));r+=(2*Math.acos(dot))**2;if(early&&(p>posLimit**2*indices.length||r>rad**2*indices.length))return null;}return {position:Math.sqrt(p/indices.length),rotation:Math.sqrt(r/indices.length)};};
 const candidates:any[]=[];let holdRunsExcluded=0,comparedFrames=0;
 for(let offset=1-a.poses.length;offset<b.poses.length;offset++){
  let startA=-1,startB=-1,endA=0,endB=0,ps=0,rs=0,count=0;
  const flush=()=>{if(startA<0)return;const seconds=Math.min(a.times[endA]-a.times[startA],b.times[endB]-b.times[startB]);if(seconds+1e-9>=min){let excursionP=0,excursionR=0,excursionBP=0,excursionBR=0;for(let i=startA;i<=endA;i++){const d=difference(a.poses[startA],a.poses[i])!;excursionP=Math.max(excursionP,d.position);excursionR=Math.max(excursionR,d.rotation);const db=difference(b.poses[startB],b.poses[startB+i-startA])!;excursionBP=Math.max(excursionBP,db.position);excursionBR=Math.max(excursionBR,db.rotation);}const held=(excursionP<.025&&excursionR<5*Math.PI/180)||(excursionBP<.025&&excursionBR<5*Math.PI/180);if(held&&!includeHolds)holdRunsExcluded++;else{const window=(s:MotionSignature,lo:number,hi:number)=>({start:s.times[lo],end:s.times[hi],from:s.times[lo]/s.duration,to:s.times[hi]/s.duration,rootDisplacement:s.roots[hi].map((v,k)=>v-s.roots[lo][k]),...(s.bodies?{bodyDisplacement:s.bodies[hi].map((v,k)=>v-s.bodies![lo][k])}:{})});candidates.push({a:window(a,startA,endA),b:window(b,startB,endB),duration:seconds,positionRmsMeters:Math.sqrt(ps/count),rotationRmsDegrees:Math.sqrt(rs/count)*180/Math.PI,classification:held?'shared-hold':'shared-motion-candidate',motionExcursionMeters:excursionP,motionExcursionDegrees:excursionR*180/Math.PI,otherMotionExcursionMeters:excursionBP,otherMotionExcursionDegrees:excursionBR*180/Math.PI,samples:count});}}startA=-1;count=ps=rs=0;};
  for(let i=Math.max(0,-offset);i<a.poses.length&&i+offset<b.poses.length;i++){const j=i+offset;comparedFrames++;const d=difference(a.poses[i],b.poses[j],true);if(d&&d.position<=posLimit&&d.rotation<=rad){if(startA<0){startA=i;startB=j;}endA=i;endB=j;ps+=d.position**2;rs+=d.rotation**2;count++;}else flush();}flush();
 }
 candidates.sort((x,y)=>y.duration-x.duration||x.rotationRmsDegrees-y.rotationRmsDegrees||x.positionRmsMeters-y.positionRmsMeters);
 const matches:any[]=[];const overlap=(x:any,y:any)=>Math.max(0,Math.min(x.end,y.end)-Math.max(x.start,y.start))/Math.max(1e-9,Math.min(x.end-x.start,y.end-y.start));for(const c of candidates){if(matches.some(m=>overlap(m.a,c.a)>.5&&overlap(m.b,c.b)>.5))continue;matches.push(c);if(matches.length===limit)break;}
 return {algorithm:'same-speed-diagonal-windows-v1',sampleRate:30,bodyPart:group,joints:indices.map(i=>commonJoints[i]),thresholds:{minDuration:min,positionToleranceMeters:posLimit,rotationToleranceDegrees:rotLimit,includeHolds},matches,holdRunsExcluded,comparedFrames,notes:['Positions are pelvis-relative normalized meters; rotations are local joint quaternions. Root and pelvis travel are reported separately and not part of the similarity gate; fingers and joint scales are not compared.','Fixed playback speed and model facing; no retiming, mirroring or yaw alignment. Endpoints have at most one sample interval of resolution.','Similar motion is a reusable-source candidate, not proof of common provenance or safe blending. Partial-body matches cannot be extracted as whole-body shared movements without further authoring.']};
}
