import * as T from 'three/webgpu';
import {Action,duration} from './action';
import {CharacterPlayer} from './player';
import {commonJoints} from './common-motion';
export type ContactIntent={foot:'left'|'right';start:number;end:number;origin?:string};
export const qualityDefaults={floorY:0,footHeightTolerance:.05,footSpeedTolerance:.15,minContactDuration:.1,contactDriftTolerance:.03,boneLengthRelativeTolerance:.02,scaleRelativeTolerance:.02,rootVelocityJumpTolerance:.5,jointVelocityJumpTolerance:1,angularVelocityJumpTolerance:360};
export function qualityOptions(value:any={}){
 if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(k=>!Object.hasOwn(qualityDefaults,k)))throw Error('Invalid motion-quality thresholds');
 const out={...qualityDefaults,...value};for(const [k,v]of Object.entries(out))if(!Number.isFinite(v)||(k==='floorY'?Math.abs(v as number)>10:(v as number)<=0||(v as number)>({footHeightTolerance:1,footSpeedTolerance:10,minContactDuration:10,contactDriftTolerance:10,boneLengthRelativeTolerance:2,scaleRelativeTolerance:2,rootVelocityJumpTolerance:100,jointVelocityJumpTolerance:100,angularVelocityJumpTolerance:10000} as any)[k]))throw Error('Invalid motion-quality threshold '+k);
 return out;
}
export function qualityRequest(total:number,args:any){
 const start=args.start===undefined?0:args.start,end=args.end===undefined?total:args.end;
 if(!Number.isFinite(total)||total<=0||total>30||!Number.isFinite(start)||!Number.isFinite(end)||start<0||end>total||end-start<1e-6)throw Error('Use a nonempty motion-quality window within an action up to 30 seconds');
 const contacts:ContactIntent[]=args.contacts===undefined?[]:args.contacts;if(!Array.isArray(contacts)||contacts.length>16||contacts.some(c=>!c||Object.keys(c).some(k=>!['foot','start','end'].includes(k))||!['left','right'].includes(c.foot)||!Number.isFinite(c.start)||!Number.isFinite(c.end)||c.start<0||c.end>total||c.end-c.start<1e-6))throw Error('Invalid declared contact intervals');
 return {start,end,thresholds:qualityOptions(args.thresholds),contacts:contacts.map(c=>({...c,origin:'caller-contact-intent'}))};
}
type Sample={time:number;root:T.Vector3;body:T.Vector3;positions:T.Vector3[];rotations:T.Quaternion[];feet:T.Vector3[];lengths:number[];scales:number[][]};
const angular=(a:T.Quaternion,b:T.Quaternion,dt:number)=>{const q=b.clone().multiply(a.clone().invert()).normalize();if(q.w<0){q.x*=-1;q.y*=-1;q.z*=-1;q.w*=-1;}const n=Math.hypot(q.x,q.y,q.z);return n<1e-10?new T.Vector3():new T.Vector3(q.x,q.y,q.z).multiplyScalar(2*Math.atan2(n,q.w)/(n*dt));};
const velocity=(a:T.Vector3,b:T.Vector3,dt:number)=>b.clone().sub(a).divideScalar(dt);
export function inspectMotionQuality(player:CharacterPlayer,action:Action,args:any={},recipe?:any){
 const total=duration(action),request=qualityRequest(total,args),{start,end,thresholds}=request,dt=1/60,model=player.model;
 const joints=commonJoints.map(n=>model.getObjectByName(n)!);const feet=['ball_l','ball_r'].map(n=>model.getObjectByName(n)!);
 if([...joints,...feet].some(n=>!n))throw Error('Unsupported motion-quality rig');
 const bones=player.restTransforms.map(e=>e.bone),links=bones.filter(b=>(b.parent as T.Bone)?.isBone);
 // Reference is the imported rest rig, before action sampling, rather than a possibly distorted first pose.
 for(const e of player.restTransforms){e.bone.position.copy(e.p);e.bone.quaternion.copy(e.q);e.bone.scale.copy(e.s);}model.position.copy(player.rootPosition);model.quaternion.copy(player.rootRotation);model.scale.copy(player.baseScale);model.updateWorldMatrix(true,true);
 const length=(b:T.Object3D)=>b.getWorldPosition(new T.Vector3()).distanceTo(b.parent!.getWorldPosition(new T.Vector3()));
 const baselineLengths=links.map(length),baselineScales=[player.baseScale.toArray(),...player.restTransforms.map(e=>e.s.toArray())];
 if(baselineScales.some(s=>s.some(v=>Math.abs(v)<1e-10)))throw Error('Unsupported zero rest scale');
 const sampleCache=new Map<string,Sample>();
 const sample=(time:number):Sample=>{time=Math.max(0,Math.min(total,time));const key=time.toFixed(9),cached=sampleCache.get(key);if(cached)return cached;player.sample(action,time);model.updateWorldMatrix(true,true);const s={time,root:model.getWorldPosition(new T.Vector3()),body:joints[0].getWorldPosition(new T.Vector3()),positions:joints.map(n=>n.getWorldPosition(new T.Vector3())),rotations:joints.map(n=>n.quaternion.clone()),feet:feet.map(n=>n.getWorldPosition(new T.Vector3())),lengths:links.map(length),scales:[model.scale.toArray(),...bones.map(b=>b.scale.toArray())]};sampleCache.set(key,s);return s;};
 const phaseBoundaries:any[]=[],joinIntents:ContactIntent[]=[];let at=0;
 action.phases.forEach((p,i)=>{const next=at+p.duration;if(i>0)phaseBoundaries.push({time:at,index:i,before:action.phases[i-1].id,after:p.id,kind:p.id.startsWith('join-')?'join-start':action.phases[i-1].id.startsWith('join-')?'join-end':'phase-boundary'});const step=p.id.startsWith('join-')?Number(p.id.slice(5)):NaN,contact=recipe?.steps?.[step]?.contact;if(['left','right'].includes(contact))joinIntents.push({foot:contact,start:at,end:next,origin:'recipe-anchor-intent'});at=next;});
 const contacts=[...request.contacts,...joinIntents].filter(c=>c.end>=start&&c.start<=end).map(c=>({...c,start:Math.max(start,c.start),end:Math.min(end,c.end)})).filter(c=>c.end>c.start);
 const times=[start,end,...phaseBoundaries.filter(b=>b.time>start&&b.time<end).map(b=>b.time),...contacts.flatMap(c=>[c.start,c.end])];for(let i=Math.ceil(start*60);i/60<end;i++)times.push(i/60);
 times.sort((a,b)=>a-b);const samples=times.filter((t,i)=>!i||t-times[i-1]>1e-8).map(sample);
 const flags:any[]=[];const flag=(code:string,subject:string,window:any,evidence:any)=>flags.push({code,severity:'review',subject,window,evidence,supportedFixes:['Inspect this window in Studio','Select another source or revise the indicated connection/intent']});
 const boneLengths=links.map((bone,j)=>{let peak=0,peakTime=start,min=Infinity,max=-Infinity;for(const s of samples){const l=s.lengths[j];min=Math.min(min,l);max=Math.max(max,l);const error=baselineLengths[j]>1e-8?Math.abs(l/baselineLengths[j]-1):0;if(error>peak){peak=error;peakTime=s.time;}}const kind=bone.name==='pelvis'&&bone.parent!.name==='root'?'body-offset':'skeletal-link';const record={bone:bone.name,parent:bone.parent!.name,kind,restMeters:baselineLengths[j],minMeters:min,maxMeters:max,maxRelativeChange:peak,peakTime,measurable:baselineLengths[j]>1e-8};if(kind==='skeletal-link'&&peak>thresholds.boneLengthRelativeTolerance)flag('rig/bone-length',`/rig/${bone.name}`,{start:Math.max(start,peakTime-dt),end:Math.min(end,peakTime+dt)},record);return record;});
 const scaleChanges=[model,...bones].map((bone,j)=>{let peak=0,peakTime=start;for(const s of samples){const error=Math.max(...s.scales[j].map((v,k)=>Math.abs(v/baselineScales[j][k]-1)));if(error>peak){peak=error;peakTime=s.time;}}const record={target:j===0?'$root':bone.name,maxRelativeChange:peak,peakTime};if(peak>thresholds.scaleRelativeTolerance)flag('rig/scale',`/rig/${record.target}`,{start:Math.max(start,peakTime-dt),end:Math.min(end,peakTime+dt)},record);return record;}).filter(s=>s.maxRelativeChange>1e-8);
 const travel=(key:'root'|'body')=>({delta:samples.at(-1)![key].clone().sub(samples[0][key]).toArray(),distance:samples.slice(1).reduce((n,s,i)=>n+s[key].distanceTo(samples[i][key]),0)});
 const footStats=(side:number,range:Sample[])=>{const origin=range[0].feet[side];let maxHorizontalDrift=0,path=0,maxSpeed=0;for(let i=0;i<range.length;i++){const s=range[i];maxHorizontalDrift=Math.max(maxHorizontalDrift,Math.hypot(s.feet[side].x-origin.x,s.feet[side].z-origin.z));if(i){const distance=s.feet[side].distanceTo(range[i-1].feet[side]);path+=distance;maxSpeed=Math.max(maxSpeed,distance/(s.time-range[i-1].time));}}return {maxHorizontalDriftMeters:maxHorizontalDrift,pathMeters:path,maxSpeedMetersPerSecond:maxSpeed,minHeightMeters:Math.min(...range.map(s=>s.feet[side].y-thresholds.floorY)),maxHeightMeters:Math.max(...range.map(s=>s.feet[side].y-thresholds.floorY)),sampleCount:range.length};};
 const candidateContacts:any[]=[];
 for(let side=0;side<2;side++){let began=-1;const flush=(last:number)=>{if(began>=0&&samples[last].time-samples[began].time>=thresholds.minContactDuration-1e-9){const range=samples.slice(began,last+1);candidateContacts.push({foot:side?'right':'left',start:range[0].time,end:range.at(-1)!.time,status:'candidate-not-confirmed',...footStats(side,range)});}began=-1;};samples.forEach((s,i)=>{const adjacent=[i? s.feet[side].distanceTo(samples[i-1].feet[side])/(s.time-samples[i-1].time):0,i+1<samples.length?s.feet[side].distanceTo(samples[i+1].feet[side])/(samples[i+1].time-s.time):0];const matches=Math.abs(s.feet[side].y-thresholds.floorY)<=thresholds.footHeightTolerance&&Math.max(...adjacent)<=thresholds.footSpeedTolerance;if(matches){if(began<0)began=i;}else flush(i-1);});flush(samples.length-1);}
 const declaredContacts=contacts.map((c,i)=>{const range=samples.filter(s=>s.time>=c.start-1e-9&&s.time<=c.end+1e-9),stats=footStats(c.foot==='left'?0:1,range),record={...c,status:'intent-not-confirmed',...stats};if(stats.maxHorizontalDriftMeters>thresholds.contactDriftTolerance)flag('contact/drift',`/contacts/${i}`,{start:c.start,end:c.end},record);if(Math.max(Math.abs(stats.minHeightMeters),Math.abs(stats.maxHeightMeters))>thresholds.footHeightTolerance)flag('contact/height',`/contacts/${i}`,{start:c.start,end:c.end},record);return record;});
 const seams=phaseBoundaries.filter(b=>b.time>=start&&b.time<=end).map(b=>{const before=sample(b.time-dt),center=sample(b.time),after=sample(b.time+dt),d0=center.time-before.time,d1=after.time-center.time;const root0=velocity(before.root,center.root,d0),root1=velocity(center.root,after.root,d1),body0=velocity(before.body,center.body,d0),body1=velocity(center.body,after.body,d1);const linear=joints.map((_,j)=>velocity(center.positions[j],after.positions[j],d1).sub(root1).sub(velocity(before.positions[j],center.positions[j],d0).sub(root0)).length());const rotation=joints.map((_,j)=>angular(center.rotations[j],after.rotations[j],d1).sub(angular(before.rotations[j],center.rotations[j],d0)).length()*180/Math.PI);const record={...b,window:{start:before.time,end:after.time},rootVelocityBefore:root0.toArray(),rootVelocityAfter:root1.toArray(),rootVelocityJumpMetersPerSecond:root1.distanceTo(root0),bodyVelocityJumpMetersPerSecond:body1.distanceTo(body0),jointVelocityJumpRmsMetersPerSecond:Math.sqrt(linear.reduce((s,v)=>s+v*v,0)/linear.length),angularVelocityJumpRmsDegreesPerSecond:Math.sqrt(rotation.reduce((s,v)=>s+v*v,0)/rotation.length),peakJoint:commonJoints[linear.indexOf(Math.max(...linear))],peakAngularJoint:commonJoints[rotation.indexOf(Math.max(...rotation))]};if(record.rootVelocityJumpMetersPerSecond>thresholds.rootVelocityJumpTolerance||record.jointVelocityJumpRmsMetersPerSecond>thresholds.jointVelocityJumpTolerance||record.angularVelocityJumpRmsDegreesPerSecond>thresholds.angularVelocityJumpTolerance)flag('connection/velocity-change',`/phases/${b.index}`,record.window,record);return record;});
 const velocities=joints.map((node,j)=>{let maxLinear=0,maxAngular=0,linearTime=start,angularTime=start;for(let i=1;i<samples.length;i++){const a=samples[i-1],b=samples[i],step=b.time-a.time,linear=b.positions[j].distanceTo(a.positions[j])/step,rotation=angular(a.rotations[j],b.rotations[j],step).length()*180/Math.PI;if(linear>maxLinear){maxLinear=linear;linearTime=b.time;}if(rotation>maxAngular){maxAngular=rotation;angularTime=b.time;}}return {joint:node.name,maxWorldSpeedMetersPerSecond:maxLinear,linearPeakTime:linearTime,maxLocalAngularSpeedDegreesPerSecond:maxAngular,angularPeakTime:angularTime};});
 return {schemaVersion:1,algorithm:'rig-motion-quality-v1',window:{start,end},sampleRate:60,sampledFrames:samples.length,thresholds,thresholdStatus:'Configured review thresholds, not universal physical limits',boneLengths,scaleChanges,feet:{left:footStats(0,samples),right:footStats(1,samples)},candidateContacts,declaredContacts,travel:{root:travel('root'),pelvis:travel('body')},velocities,seams,diagnostics:flags,inspectionWindows:flags.map(f=>({code:f.code,subject:f.subject,...f.window})),status:flags.length?'review-needed':'no-configured-flags',physicalValidation:'not-performed',unknowns:['anatomical facing','physical support and balance','collision and equipment','contact confirmation'],notes:['All distances are normalized world meters, times seconds; floor Y is caller-configured. Feet use ball joint pivots, not sole geometry.','60Hz finite differences plus exact phase/contact/window endpoints; seams use samples up to 1/60s either side and may include neighboring short phases.','Joint seam linear velocities remove model-root translation; local angular velocities are quaternion differences in parent coordinates. Peak joint linear speeds are world-space.','Candidate contacts use height AND adjacent speed. Declared contacts are intent, never automatically confirmed. Metadata endpoint support is not treated as a full-clip contact declaration.','The root-bone to pelvis link is a body offset, not anatomical bone length; its variation is measured but never flagged as bone distortion.','Bone lengths/scales compare to imported rest rig, including model-root scale. Authored squash/stretch may intentionally trigger review.','No configured flags does not certify natural motion. Sparse sampling can miss subframe events. Anatomical facing is not inferred.']};
}
