import * as T from 'three/webgpu';
import {Action,duration} from './action';
import {CharacterPlayer} from './player';
const joints=['pelvis','spine_03','Head','upperarm_l','lowerarm_l','hand_l','upperarm_r','lowerarm_r','hand_r','thigh_l','calf_l','foot_l','thigh_r','calf_r','foot_r'];
export type Support='both'|'left'|'right'|'none'|'unknown';
export type Endpoint={pose:'upright'|'low'|'airborne';headHeight:number;root:number[];forward:number[];positions:number[][];rotations:number[][];feet:{left:{height:number;speed:number};right:{height:number;speed:number}};supportHint:Support};
export type MovementProfile={version:1;sourceRevision:number;entry:Endpoint;exit:Endpoint;travel:{rootDelta:number[];bodyDelta:number[];rootDistance:number};review?:{entrySupport:Support;exitSupport:Support;notes:string}};
// Endpoint hints use ball-joint proximity and short-window speed. They are not contacts.
export function profileMovement(player:CharacterPlayer,a:Action,revision:number):MovementProfile{
 const model=player.model,total=duration(a),window=Math.min(.05,total/2);
 const sample=(t:number)=>{player.sample(a,t);return {root:model.getWorldPosition(new T.Vector3()),forward:new T.Vector3(0,0,1).applyQuaternion(model.getWorldQuaternion(new T.Quaternion())),body:model.getObjectByName('pelvis')!.getWorldPosition(new T.Vector3()),points:joints.map(n=>model.getObjectByName(n)!.getWorldPosition(new T.Vector3())),rotations:joints.map(n=>model.getObjectByName(n)!.quaternion.toArray()),feet:['ball_l','ball_r'].map(n=>model.getObjectByName(n)!.getWorldPosition(new T.Vector3()))};};
 const entry=sample(0),exit=sample(total),after=sample(window),before=sample(total-window);
 const endpoint=(s:ReturnType<typeof sample>,near:ReturnType<typeof sample>):Endpoint=>{const feet={left:{height:s.feet[0].y,speed:s.feet[0].distanceTo(near.feet[0])/window},right:{height:s.feet[1].y,speed:s.feet[1].distanceTo(near.feet[1])/window}};const left=Math.abs(feet.left.height)<=.05&&feet.left.speed<=.15,right=Math.abs(feet.right.height)<=.05&&feet.right.speed<=.15,headHeight=s.points[2].y;return {pose:Math.min(feet.left.height,feet.right.height)>.15?'airborne':headHeight<1.15?'low':'upright',headHeight,root:s.root.toArray(),forward:s.forward.toArray(),positions:s.points.map(p=>p.clone().sub(s.root).toArray()),rotations:s.rotations,feet,supportHint:left&&right?'both':left?'left':right?'right':'none'};};
 let rootDistance=0,previous=entry.root;for(let i=1;i<=30;i++){const current=sample(total*i/30).root;rootDistance+=current.distanceTo(previous);previous=current;}
 return {version:1,sourceRevision:revision,entry:endpoint(entry,after),exit:endpoint(exit,before),travel:{rootDelta:exit.root.clone().sub(entry.root).toArray(),bodyDelta:exit.body.clone().sub(entry.body).toArray(),rootDistance}};
}
// facing 'continue' compares as the composer joins with facing continuation: the incoming entry is first turned about the
// vertical so its hip line (left hip to right hip, seen from above) has the heading of the outgoing exit's. Without it two
// movements that differ only in which way they face look far apart. The turn is applied to the joint positions and to the
// pelvis rotation (through the root's own heading, taken from the stored forward vector); other joints are local and unaffected.
export function compareEndpoints(from:MovementProfile,to:MovementProfile,facing:'source'|'continue'='source'){const a=from.exit;let b=to.entry,turnDegrees=0;
 if(facing==='continue'){const heading=(e:Endpoint)=>{const h=e.positions[9].map((v,k)=>v-e.positions[12][k]);return Math.hypot(h[0],h[2])>Math.abs(h[1])?Math.atan2(h[0],h[2]):null;},out=heading(a),into=heading(b);
  if(out!==null&&into!==null){const yaw=out-into,turn=new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),yaw),rootYaw=(e:Endpoint)=>new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),Math.atan2(e.forward[0],e.forward[2])),ra=rootYaw(a),rb=rootYaw(b);turnDegrees=((yaw*180/Math.PI+540)%360)-180;
   // pelvis as the outgoing root would hold it: ra^-1 . turn . rb . pelvis
   b={...b,positions:b.positions.map(p=>new T.Vector3(p[0],p[1],p[2]).applyQuaternion(turn).toArray()),rotations:b.rotations.map((q,i)=>i?q:ra.clone().invert().multiply(turn).multiply(rb).multiply(new T.Quaternion(q[0],q[1],q[2],q[3])).toArray())};}}
 const poseRms=Math.sqrt(a.positions.reduce((s,p,i)=>s+p.reduce((n,v,k)=>n+(v-b.positions[i][k])**2,0),0)/a.positions.length);const rotationRms=Math.sqrt(a.rotations.reduce((s,q,i)=>{const dot=Math.min(1,Math.abs(q.reduce((n,v,k)=>n+v*b.rotations[i][k],0)));return s+(2*Math.acos(dot))**2;},0)/a.rotations.length);const x=from.review?.exitSupport??a.supportHint,y=to.review?.entrySupport??b.supportHint;const supportConflict=x!=='unknown'&&y!=='unknown'&&x!=='none'&&y!=='none'&&x!=='both'&&y!=='both'&&x!==y;const score=poseRms+.15*rotationRms+(supportConflict?.2:0);return {facing,turnDegrees,poseRmsMeters:poseRms,rotationRmsDegrees:rotationRms*180/Math.PI,score,fit:poseRms<.12&&rotationRms<.4&&!supportConflict?'near':'needs-transition',supportConflict,fromSupport:x,toSupport:y,reviewed:!!from.review&&!!to.review,rootGapMeters:Math.hypot(...a.root.map((v,i)=>v-b.root[i])),note:'Heuristic endpoint match; inspect the full connection, contact and balance.'};}
