// Offline, fixed-asset adapter. No arbitrary model importer or executable asset code.
import {readFile,writeFile} from 'node:fs/promises';import crypto from 'node:crypto';import * as T from 'three/webgpu';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
globalThis.ProgressEvent=class{constructor(type,init){Object.assign(this,init);this.type=type;}};
const bytes=await readFile('editor/source/ual2/UAL2_Standard.glb');const j=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)));j.buffers[0].uri='data:application/octet-stream;base64,'+bytes.subarray(28+bytes.readUInt32LE(12)).toString('base64');j.materials=j.materials.map(()=>({}));delete j.images;delete j.textures;
const source=await new GLTFLoader().parseAsync(JSON.stringify(j),'');const tb=await readFile('editor/assets/character.glb');const target=await new GLTFLoader().parseAsync(tb.buffer.slice(tb.byteOffset,tb.byteOffset+tb.byteLength),'');
source.scene.updateMatrixWorld(true);target.scene.updateMatrixWorld(true);const bones=[];target.scene.traverse(b=>{if(b.isBone)bones.push(b)});const rest=bones.map(b=>({b,p:b.position.clone(),q:b.quaternion.clone(),w:b.getWorldQuaternion(new T.Quaternion()),src:source.scene.getObjectByName(b.name)}));if(rest.some(e=>!e.src?.isBone))throw Error('Unsupported source skeleton');for(const e of rest)e.sw=e.src.getWorldQuaternion(new T.Quaternion());
const holder=new T.Group(),scale=1.85/new T.Box3().setFromObject(target.scene).getSize(new T.Vector3()).y;holder.scale.setScalar(scale);holder.add(target.scene);holder.updateMatrixWorld(true);const sp=source.scene.getObjectByName('pelvis'),dp=target.scene.getObjectByName('pelvis'),sr=sp.getWorldPosition(new T.Vector3()),dr=dp.getWorldPosition(new T.Vector3());const mixer=new T.AnimationMixer(source.scene);const movements=[];
for(const clip of source.animations){
 mixer.stopAllAction();const animation=mixer.clipAction(clip);animation.play();animation.paused=true;
 const tracks=rest.map(e=>({target:e.b.name,property:'rotation',mode:'absolute',interpolation:'linear',keys:[]}));const pelvis={target:'pelvis',property:'position',mode:'absolute',interpolation:'linear',keys:[]};const count=Math.min(240,Math.ceil(clip.duration*60));
 for(let i=0;i<=count;i++){const time=i===count?clip.duration:i*clip.duration/count;animation.time=time;mixer.update(0);source.scene.updateMatrixWorld(true);for(const e of rest){e.b.position.copy(e.p);e.b.quaternion.copy(e.q);}holder.updateMatrixWorld(true);dp.position.copy(dp.parent.worldToLocal(dr.clone().add(sp.getWorldPosition(new T.Vector3()).sub(sr).multiplyScalar(scale))));holder.updateMatrixWorld(true);
  for(let k=0;k<rest.length;k++){const e=rest[k],world=e.src.getWorldQuaternion(new T.Quaternion()).multiply(e.sw.clone().invert()).multiply(e.w);e.b.quaternion.copy(e.b.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(world)).normalize();holder.updateMatrixWorld(true);tracks[k].keys.push({time,value:e.b.quaternion.toArray()});}pelvis.keys.push({time,value:dp.position.toArray()});
 }
 tracks.push(pelvis);for(const t of tracks){if(t.keys.every(k=>k.value.every((v,i)=>Math.abs(v-t.keys[0].value[i])<1e-6)))t.keys=[t.keys[0]];}
 const name=clip.name.replaceAll('_',' '),id='move-ual2-'+clip.name.toLowerCase().replaceAll('_','-');const phases=[];let remaining=clip.duration,index=0;while(remaining>0){const duration=Math.min(10,remaining);phases.push({id:'motion-'+index++,name,intent:'Adapted source motion; contact and gameplay require review',duration,kind:clip.name.includes('Idle')?'hold':'move',clip:'A_TPose',from:0,to:0});remaining-=duration;}
 const action={version:2,rig:'quaternius-ual1',id,name:'UAL2 · '+name,phases,tracks,cues:[]};const metadata={source:'Quaternius UAL2 Standard · '+clip.name+' · CC0',support:'unknown',travel:'source',notes:'Fixed-rig adaptation retaining target bone lengths. Original '+clip.name+'; '+(count/clip.duration).toFixed(1)+' Hz baked sampling. Props, collisions, root/controller integration and foot contacts are not automatically supplied.'};movements.push({action,metadata});console.log(clip.name,clip.duration.toFixed(3),tracks.reduce((n,t)=>n+t.keys.length,0));
}
const hash=crypto.createHash('sha256').update(bytes).digest('hex');await writeFile('runtime/ual2-library.json',JSON.stringify({version:1,sourceHash:hash,movements}));await writeFile('editor/source/ual2/provenance.json',JSON.stringify({publisher:'Quaternius',source:'https://quaternius.com/packs/universalanimationlibrary2.html',edition:'Free Standard',license:'CC0-1.0',sha256:hash,clips:movements.map(m=>m.metadata.source),adapter:'authoring/source/import-ual2.mjs',rootMotionEdition:false},null,2));console.log('Imported',movements.length);
