import {request} from '../../cli-lib.mjs';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const call=(n,a)=>request('http://127.0.0.1:5174',n,a),dir='authoring/reviews/slide',input=JSON.parse(await readFile(dir+'/inputs.json','utf8')),id='slide-contract-study';
const {result:library}=await call('inspect_movement_library',{query:'locomotion-slide',limit:10});assert.equal(library.items.length,3);
const {result:actions}=await call('list_actions',{}),step=s=>{const m=library.items.find(m=>m.id==='move-ual2-slide-'+s);return {movementId:m.id,revision:m.revision,speed:1};};
await call('append_action_run_event',{runId:input.runId,phase:'source-review',note:'Nine source frames per camera reviewed. Slide Start goes from running stride to low seated slide; Loop sustains it; Exit returns to running stride (not standing/guard). All roots stationary, pelvis lowers/rises; future controller supplies travel. No measured foot contacts; body/hand support not covered by current inspection. Added source-hash-pinned candidate semantics and two links; source tracks unchanged.'});
const spec={schemaVersion:1,rig:'quaternius-ual1',id,name:'Slide · Enter → Sustain → Exit',intent:'From a running stride, enter a low slide, sustain it briefly and rise back into a running stride. In-place motion preview; controller supplies directional travel.',steps:[step('start'),{...step('loop'),connection:{contractId:'slide-start-to-loop',duration:.06}},{...step('exit'),connection:{contractId:'slide-loop-to-exit',duration:.06}}]},expectedRevision=actions.find(a=>a.id===id)?.revision??0;
const {result:checked}=await call('build_action_spec',{spec,expectedRevision,commit:false});const built=await call('build_action_spec',{spec,expectedRevision,commit:true});const {result:report}=await call('inspect_motion_quality',{actionId:id,sourceRevision:built.result.revision});
const diagnostics=[];for(const w of built.result.receipt.inspection.slice(1)){const {result:d}=await call('get_diagnostics',{actionId:id,time:(w.joinStart+w.start)/2});diagnostics.push({step:w.step,revision:d.revision,duration:d.duration,warnings:d.warnings,peakGraphSpeed:Math.max(...d.poseSpeed)});}
await writeFile(dir+'/build.json',JSON.stringify({at:new Date().toISOString(),runId:input.runId,checked,built,report,diagnostics},null,2)+'\n');
const times=new Set(Array.from({length:9},(_,i)=>report.window.end*i/8));for(const w of built.result.receipt.inspection.slice(1))for(const t of [w.joinStart,(w.joinStart+w.start)/2,w.start])times.add(t);
await writeFile(dir+'/joined-capture-cases.json',JSON.stringify([[id,[...times].sort((a,b)=>a-b)]],null,2)+'\n');await call('set_preview',{actionId:id,time:0,playing:false,loop:false,camera:'Side',speed:1});
console.log(JSON.stringify({id,duration:built.result.duration,buildClientMs:built.clientElapsedMs,seams:report.seams,flags:report.diagnostics}));
