import {request} from '../../cli-lib.mjs';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const dir='authoring/reviews/slide',call=(n,a)=>request('http://127.0.0.1:5174',n,a),input=JSON.parse(await readFile(dir+'/inputs.json','utf8')),b=JSON.parse(await readFile(dir+'/build.json','utf8')),f=JSON.parse(await readFile(dir+'/joined-frames/frames.json','utf8'));
const {result:library}=await call('inspect_movement_library',{query:'locomotion-slide',limit:10}),{result:reviews}=await call('get_contract_reviews',{}),{result:actions}=await call('list_actions',{});
for(const m of library.items){const pin=input.library.items.find(s=>s.id===m.id);assert.equal(m.revision,pin.revision);assert.equal(m.motionHash,pin.motionHash);}
const action=actions.find(a=>a.id===b.built.result.actionId);assert.equal(action.revision,f.sourceActions[action.id].revision);const {result:quality}=await call('inspect_motion_quality',{actionId:action.id,sourceRevision:action.revision});assert.equal(quality.motionHash,f.sourceActions[action.id].motionHash);
await call('append_action_run_event',{runId:input.runId,phase:'visual-review',note:'Inspected exact join start/middle/end in Front/Side plus whole action progression. Both 0.06s no-anchor joins preserve the low seated pose coherently, with no configured motion flags. Sources enter from and exit to running stride. Foot pivots remain above floor; body/hand support and physical balance unverified. Record seam support only, no foot contact approvals. Browser replay initiated; completion checked separately.'});
const results=[];
for(const [from,to,contractId,step] of [['start','loop','slide-start-to-loop',1],['loop','exit','slide-loop-to-exit',2]]) {
 const revision=s=>library.items.find(m=>m.id==='move-ual2-slide-'+s).revision;
 results.push(await call('review_connection_policy',{contractId,fromRevision:revision(from),toRevision:revision(to),actionId:action.id,actionRevision:action.revision,step,expectedReviewRevision:reviews.seams.find(s=>s.contractId===contractId)?.reviewRevision??0,decision:'supported',views:['Front','Side'],notes:'Sampled LLM Front/Side review of exact join start/mid/end: closely matching low slide poses; numerical seam bounds pass at 1×→1×,0.06s,no anchor. This supports only the tested seam configuration; body/hand support, floor collision, physical balance and controller travel remain unverified.',artifacts:[dir+'/join-sheet.png',dir+'/joined-frames/frames.json',dir+'/source-sheet.png']}));
}
const {result:checked}=await call('build_action_spec',{spec:action.semanticSpec,expectedRevision:action.revision,commit:false});assert.equal(checked.receipt.seamPolicies.length,2);assert.ok(checked.receipt.seamPolicies.every(p=>p.decision==='supported'&&p.matchesConfiguration));assert.equal(checked.receipt.contactIntervals.length,0);
const built=await call('build_action_spec',{spec:action.semanticSpec,expectedRevision:action.revision,commit:true});const {result:final}=await call('inspect_motion_quality',{actionId:action.id,sourceRevision:built.result.revision});assert.equal(final.motionHash,quality.motionHash);assert.equal(final.diagnostics.length,0);
await call('set_preview',{actionId:action.id,time:1.5,playing:false,loop:false,camera:'Side',speed:1});
await writeFile(dir+'/registered.json',JSON.stringify({at:new Date().toISOString(),results,checked,built,final},null,2)+'\n');
console.log(JSON.stringify({id:action.id,revision:built.result.revision,seams:built.result.receipt.seamPolicies,duration:built.result.duration,motionUnchanged:quality.motionHash===final.motionHash}));
