// Run only after inspecting the pinned sheets. This stores this pilot's LLM decisions, not automatic visual approval.
import {request} from '../../cli-lib.mjs';import {readFile,writeFile} from 'node:fs/promises';
const dir='authoring/reviews/sword-completion',input=JSON.parse(await readFile(dir+'/inputs.json','utf8')),frames=JSON.parse(await readFile(dir+'/frames/frames.json','utf8')),call=(n,a)=>request('http://127.0.0.1:5174',n,a);
const {result:reviews}=await call('get_contract_reviews',{}),{result:library}=await call('inspect_movement_library',{query:'sword-regular',limit:20}),{result:actions}=await call('list_actions',{});
for(const m of library.items){const pin=frames.sourceActions[m.id];if(!pin||pin.revision!==m.revision||pin.motionHash!==m.motionHash)throw Error('Stale visual source evidence: '+m.id);}
await call('append_action_run_event',{runId:input.runId,phase:'visual-review',note:'Inspected seven whole-body frames in both Front/Side for all six Sword sources, start/mid/end foot crops for every candidate, and both recovery joins plus shorter first join. Candidate attack/braced left foot at C1.05–1.1667 and Combo1.7167–2.0833 remains uncertain (elevated pivot; render insufficient to prove contact). Quiet recovery/standing intervals appear near ground. No full-clip support inference. Browser shorter chain replay reached its standing finish; exact sheets supply seam review evidence.'});
const results=[];
for(const suffix of ['a-rec','c','combo']){
 const id='move-ual2-sword-regular-'+suffix,m=library.items.find(m=>m.id===id),r=input.reports[id];
 const intervals=r.candidateContacts.map(c=>({foot:c.foot,start:c.start,end:c.end,decision:(suffix==='c'&&c.start<1.2||suffix==='combo'&&c.start<2.1)?'uncertain':'supported',notes:(suffix==='c'&&c.start<1.2||suffix==='combo'&&c.start<2.1)?'Braced pose with opposite leg raised; elevated foot pivot and flat render do not establish true ground support. Keep uncertain; no anchor.':'Near-ground stance in sampled Front/Side start/mid/end frames. Small measured stance drift retained; not strict planted-foot or physical balance validation.'}));
 const reply=await call('review_movement_contacts',{movementId:id,sourceRevision:m.revision,expectedReviewRevision:reviews.contacts.find(r=>r.movementId===id)?.reviewRevision??0,views:['Front','Side'],notes:'LLM sampled review of every measured candidate plus source progression. Uncovered times remain unknown. Sword prop absent on mannequin; no weapon collision, physical support or balance validation.',artifacts:[dir+'/all-contact-candidates.png',dir+'/source-'+suffix+'.png',dir+'/frames/frames.json'],intervals});results.push({operation:'review_movement_contacts',...reply});
}
for(const [contractId,from,to,id,step,decision,notes] of [
 ['regular-a-to-b','a','b','sword-tight-join-review',1,'supported','0.06s blend: endpoint poses progress smoothly in sampled Front/Side renders; both measured boundary changes below configured thresholds. Supports this exact source/speed/timing only; no anchor or physical certification. Prior 0.12s flagged policy retained in history.'],
 ['regular-b-to-c','b','c','sword-tight-join-review',2,'needs-review','0.12s blend remains nearly static at closely matched source poses; outgoing velocity-change flag persists. All five tested durations retain flags. Prefer authored Combo for full attack chain; do not stretch the blend to claim approval.'],
 ['regular-a-to-a-rec','a','a-rec','sword-a-recovery-review',1,'needs-review','Sampled Front/Side endpoint poses match, but inserted hold then recovery retains a 1.009m/s RMS change. All five tested durations flag. Keep needs-review; no threshold relaxation.'],
 ['regular-b-to-b-rec','b','b-rec','sword-b-recovery-review',1,'supported','Sampled Front/Side poses remain coherent across 0.12s hold-like blend into authored recovery. Both measured boundary changes below thresholds. Exact 1×/0.12s/no-anchor configuration only; physical balance unverified.']]){
 const action=actions.find(a=>a.id===id),pin=frames.sourceActions[id];if(action.revision!==pin.revision)throw Error('Stale action capture');const {result:r}=await call('inspect_motion_quality',{actionId:id,sourceRevision:action.revision});if(r.motionHash!==pin.motionHash)throw Error('Changed captured action hash');
 const revision=s=>library.items.find(m=>m.id==='move-ual2-sword-regular-'+s).revision;
 const reply=await call('review_connection_policy',{contractId,fromRevision:revision(from),toRevision:revision(to),actionId:id,actionRevision:action.revision,step,expectedReviewRevision:reviews.seams.find(r=>r.contractId===contractId)?.reviewRevision??0,decision,views:['Front','Side'],notes,artifacts:[dir+'/'+id+'.png',dir+'/frames/frames.json',dir+'/timing-sweep.json']});results.push({operation:'review_connection_policy',...reply});
}
await writeFile(dir+'/registered.json',JSON.stringify({at:new Date().toISOString(),runId:input.runId,results},null,2)+'\n');
const {result:closed}=await call('finish_action_run',{runId:input.runId,status:'completed',note:'Sword pilot review complete with explicit unknown/uncertain regions and two unresolved joins. Eight supported source-only contacts, two uncertain; exact A→B .06 and B→B Rec .12 supported under configured review, B→C and A→A Rec need review. Source motion unchanged; no physical certification.'});await writeFile(dir+'/review-run.json',JSON.stringify((await call('get_action_run',{runId:input.runId})).result,null,2)+'\n');
console.log(JSON.stringify({closed,contacts:results.filter(r=>r.operation==='review_movement_contacts').map(r=>({id:r.result.movementId,decisions:r.result.intervals.map(c=>c.decision)})),seams:results.filter(r=>r.operation==='review_connection_policy').map(r=>({id:r.result.contractId,decision:r.result.decision,configuration:r.result.configuration}))}));
