// Render a pair of actions as a white-model video. node pair-video.mjs payload.json out.mp4
// payload: {actions:[a,b], offsets, origins, hips, duration, width, height, fps, camera}. Frames are drawn in headless Chrome
// (software WebGL, so the result does not depend on the machine's graphics) and encoded with ffmpeg.
import {createServer} from 'node:http';import fs from 'node:fs/promises';import {resolve,dirname} from 'node:path';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import {build} from 'esbuild';import {fileURLToPath} from 'node:url';
const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'../..'),payload=JSON.parse(await fs.readFile(process.argv[2],'utf8')),out=resolve(process.argv[3]),work=out+'.frames';await fs.rm(work,{recursive:true,force:true});await fs.mkdir(work,{recursive:true});
const bundle=await build({entryPoints:[resolve(here,'pair-page.ts')],bundle:true,format:'esm',write:false,minify:true}),asset=await fs.readFile(resolve(root,'editor/assets/character.glb'));
const server=createServer((req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end('<body style="margin:0;background:#fff"><script type="module" src="/page.js"></script>');}else if(req.url==='/page.js'){res.setHeader('Content-Type','application/javascript');res.end(bundle.outputFiles[0].contents);}else if(req.url==='/character.glb')res.end(asset);else if(req.url==='/payload.json'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(payload));}else{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const require=createRequire(process.env.PLAYWRIGHT_PACKAGE_JSON||'/Users/tim/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json'),{chromium}=require('playwright');let browser;const started=performance.now();
try{browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:payload.width,height:payload.height}});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.renderReady||window.renderError,undefined,{timeout:60000});const error=await page.evaluate(()=>window.renderError);if(error)throw Error(error);
 const frames=Math.round(payload.duration*payload.fps)+1;for(let n=0;n<frames;n++){const png=await page.evaluate(t=>window.renderFrame(t),Math.min(payload.duration,n/payload.fps));await fs.writeFile(resolve(work,`f${String(n).padStart(5,'0')}.png`),Buffer.from(png.split(',')[1],'base64'));}
 execFileSync('ffmpeg',['-v','error','-y','-framerate',String(payload.fps),'-i',resolve(work,'f%05d.png'),'-c:v','libx264','-pix_fmt','yuv420p','-crf','16','-movflags','+faststart',out]);if(!process.argv.includes('--keep-frames'))await fs.rm(work,{recursive:true,force:true});
 console.log(JSON.stringify({file:out,frames,fps:payload.fps,width:payload.width,height:payload.height,camera:payload.camera,seconds:Math.round((performance.now()-started)/100)/10}));
}finally{await browser?.close();await new Promise(r=>server.close(r));}
