import {request} from '../../cli-lib.mjs';import {mkdir,writeFile,readFile} from 'node:fs/promises';
const base=process.env.STUDIO_URL||'http://127.0.0.1:5174',directory='authoring/reviews/sword';await mkdir(directory,{recursive:true});
const {result:stored}=await request(base,'get_contract_reviews',{}),{result:library}=await request(base,'inspect_movement_library',{query:'sword-regular',limit:20}),{result:actions}=await request(base,'list_actions',{});
const capture=JSON.parse(await readFile(directory+'/frames/frames.json','utf8'));
for(const id of ['move-ual2-sword-regular-a-rec','move-ual2-sword-regular-combo']){const m=library.items.find(m=>m.id===id),pin=capture.sourceActions[id];if(!m||!pin||m.revision!==pin.revision||m.motionHash!==pin.motionHash)throw Error('Visual capture stale for '+id+'; recapture before reviewing');}
const joined=actions.find(a=>a.id==='sword-joined-study'),pin=capture.sourceActions['sword-joined-study'];if(!joined||!pin||joined.revision!==pin.revision)throw Error('Joined visual capture stale');const {result:diagnostic}=await request(base,'inspect_motion_quality',{actionId:joined.id,sourceRevision:joined.revision,start:.4,end:.6});if(diagnostic.motionHash!==pin.motionHash)throw Error('Joined capture motion hash changed');
const revision=id=>{const m=library.items.find(m=>m.id===id);if(!m)throw Error('Missing source '+id);return m.revision;};
const artifacts=['authoring/reviews/sword/frames/contact-review.png','authoring/reviews/sword/frames/frames.json'];
const contactPlans=[['move-ual2-sword-regular-a-rec',.75,.96],['move-ual2-sword-regular-combo',2.85,3]].map(([movementId,start,end])=>({name:'review_movement_contacts',arguments:{movementId,sourceRevision:revision(movementId),expectedReviewRevision:stored.contacts.find(r=>r.movementId===movementId)?.reviewRevision??0,views:['Front','Side'],notes:'LLM visual review of start/mid/end renders in both cameras. Both feet remain near the floor; small stance drift is retained, not forced into a planted-foot constraint. Only these intervals are reviewed; physical support/balance unverified.',artifacts,intervals:['left','right'].map(foot=>({foot,start,end,decision:'supported',notes:'Foot appears grounded in sampled front/side renders; measured small drift is allowed. No automatic anchor.'}))}}));
const action=actions.find(a=>a.id==='sword-joined-study');if(!action)throw Error('Missing joined study');
const seamPlans=[['regular-a-to-b','a','b',1],['regular-b-to-c','b','c',2]].map(([contractId,from,to,step])=>({name:'review_connection_policy',arguments:{contractId,fromRevision:revision('move-ual2-sword-regular-'+from),toRevision:revision('move-ual2-sword-regular-'+to),actionId:action.id,actionRevision:action.revision,step,expectedReviewRevision:stored.seams.find(r=>r.contractId===contractId)?.reviewRevision??0,decision:'needs-review',views:['Front','Side'],notes:'LLM visual review of exact join start/mid/end renders in both cameras: closely matched endpoint poses and a nearly static added blend. Configured velocity-change flag remains at the outgoing boundary. Keep this exact no-anchor timing as inspected evidence, not production approval.',artifacts:['authoring/reviews/sword/frames/seam-review.png','authoring/reviews/sword/frames/frames.json']}}));
const results=[];for(const plan of [...contactPlans,...seamPlans]){const reply=await request(base,plan.name,plan.arguments);results.push({operation:plan.name,arguments:plan.arguments,...reply});}
await writeFile(directory+'/registered-reviews.json',JSON.stringify({at:new Date().toISOString(),results},null,2)+'\n');console.log(JSON.stringify(results.map(r=>({operation:r.operation,id:r.result.movementId||r.result.contractId,reviewRevision:r.result.reviewRevision,decision:r.result.decision||r.result.intervals.map(i=>i.decision)}))));
