import {ContractReviews,validateReviewData} from './contract-reviews.mjs';
import contactReviewSchema from './schemas/contact-review.schema.json';
import seamPolicySchema from './schemas/seam-policy.schema.json';
import {inspectMotionQuality,qualityRequest,qualityDefaults} from '../runtime/motion-quality';
import {sampleSignature,compareMotion,MotionSignature} from '../runtime/common-motion';
import {manifest,inspectLibrary,resolveSpec,motionHash,actionSpecSchema,conventions,contactReview,connectionPolicy,findContract} from './contracts.mjs';
import {RunLogs} from './run-log';
import {loadProject,saveProject} from './project-store.mjs';
import {reconstruct,hashFile,runProcess,defaultEnvironment,bodyParts} from './reconstruction/pipeline.mjs';
import {digest} from './reconstruction/contracts.mjs';
import {statSync,rmSync} from 'node:fs';
import {isAbsolute} from 'node:path';
import {retarget as retargetMotion} from './reconstruction/retarget';
import {readFileSync,writeFileSync,mkdirSync,renameSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import * as THREE from 'three/webgpu';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {clone as cloneRig} from 'three/addons/utils/SkeletonUtils.js';
import {Action,jump,burst,clone,validateAction,duration,rootHeight} from '../runtime/action';
import {rigManifest} from '../runtime/rig';
import {CharacterPlayer} from '../runtime/player';
import {compileKick,kickBaseline,kickLimits} from '../runtime/kick';
import ual2Library from '../runtime/ual2-library.json';
import {profileMovement,compareEndpoints,MovementProfile} from '../runtime/movement-profile';
import {adaptMovement} from '../runtime/adapt-movement';
import {seedMovements,composeMovements,MovementMetadata} from '../runtime/movements';
const object=(properties:any,required=Object.keys(properties))=>({type:'object',properties,required,additionalProperties:false});
const str={type:'string'},num={type:'number'},id={type:'string',pattern:'^[-a-z0-9]{1,48}$'};
const keySchema=object({time:{type:'number',minimum:0,maximum:30},value:{type:'array',items:num,minItems:3,maxItems:4}});
export const actionSchema=object({
 version:{const:2},rig:{const:'quaternius-ual1'},id,name:{type:'string',minLength:1,maxLength:64},
 phases:{type:'array',minItems:1,maxItems:32,items:object({id,name:str,intent:str,duration:{type:'number',minimum:.016,maximum:10},kind:{enum:['hold','fast','move','neutral']},clip:{enum:rigManifest.clips},from:{type:'number',minimum:0,maximum:1},to:{type:'number',minimum:0,maximum:1}},['id','name','intent','duration','clip','from','to'])},
 tracks:{type:'array',maxItems:198,items:object({target:{enum:['$root',...rigManifest.bones.map(b=>b.name)]},property:{enum:['rotation','position','scale']},mode:{enum:['absolute','offset']},interpolation:{enum:['linear','smooth','step']},keys:{type:'array',minItems:1,maxItems:256,items:keySchema}})},
 cues:{type:'array',maxItems:16,items:object({type:{const:'impact'},time:num,strength:{type:'number',minimum:.1,maximum:3}})}
},['version','rig','id','name','phases','tracks']);
const expected={type:'integer',minimum:0};
const previewSchema=object({actionId:id,time:{type:'number',minimum:0,maximum:30},playing:{type:'boolean'},speed:{type:'number',minimum:.05,maximum:2},loop:{type:'boolean'},view:{enum:['current','reference','both']},camera:{enum:['Orbit','Front','Side','Top']},grid:{type:'boolean'},effects:{type:'boolean'},idle:{type:'boolean'},metric:{enum:['pose','height']}},[]);
const movementMetadataSchema=object({source:{type:'string',minLength:1,maxLength:300},support:{enum:['both','left','right','unknown']},travel:{enum:['in-place','source']},notes:{type:'string',maxLength:500}});
function movementMetadata(v:any):MovementMetadata{if(!v||Object.keys(v).some(k=>!['source','support','travel','notes'].includes(k))||typeof v.source!=='string'||!v.source||v.source.length>300||typeof v.notes!=='string'||v.notes.length>500||!['both','left','right','unknown'].includes(v.support)||!['in-place','source'].includes(v.travel))throw Error('Invalid movement metadata');return clone(v);}
function validateRecipe(v:any){if(!v||!['pose-blend-v1','pose-blend-v2'].includes(v.compiler)||!Array.isArray(v.steps)||!v.steps.length||v.steps.length>8||!Array.isArray(v.warnings)||v.warnings.some((w:any)=>typeof w!=='string'||w.length>500)||v.steps.some((s:any,i:number)=>!s||typeof s.movementId!=='string'||!s.movementId.startsWith('move-')||!Number.isInteger(s.revision)||s.revision<1||!Number.isFinite(s.speed)||s.speed<.5||s.speed>1.5||!Number.isFinite(s.transition)||s.transition<0||s.transition>1||i===0&&s.transition!==0||i>0&&s.transition===0||s.contact!==undefined&&!['left','right'].includes(s.contact)||s.blend!==undefined&&!['pose','velocity'].includes(s.blend)||s.travel!==undefined&&!['source','continue'].includes(s.travel)))throw Error('Invalid action recipe');return clone(v);}
export const toolDefinitions=[
 {name:'get_contract_reviews',description:'Read stored contact/seam reviews and retained history, including stale revision/hash pins. No writes; current manifests hide stale evidence.',inputSchema:object({movementId:id,contractId:id},[])},
 {name:'review_movement_contacts',description:'Record bounded source intervals after visual review. Service remeasures contact intent and pins revision/hash; supported decisions require configured height/speed/drift bounds. Uncovered time stays unknown, no automatic anchoring.',inputSchema:object({movementId:id,sourceRevision:expected,expectedReviewRevision:expected,intervals:{...contactReviewSchema.properties.intervals,items:object(Object.fromEntries(Object.entries(contactReviewSchema.properties.intervals.items.properties).filter(([k])=>k!=='measurements')))},views:contactReviewSchema.properties.views,notes:contactReviewSchema.properties.notes,artifacts:contactReviewSchema.properties.artifacts},['movementId','sourceRevision','expectedReviewRevision','intervals','views','notes'])},
 {name:'review_connection_policy',description:'Record visual seam review for one curated source pair on an existing compiled recipe. Pins both sources and exact speed/blend/no-anchor configuration. Supported requires no configured flags; needs-review and rejected remain explicit. Does not modify motion.',inputSchema:object({contractId:id,fromRevision:expected,toRevision:expected,actionId:id,actionRevision:expected,step:{type:'integer',minimum:1,maximum:7},expectedReviewRevision:expected,decision:{enum:['supported','needs-review','rejected']},views:seamPolicySchema.properties.views,notes:seamPolicySchema.properties.notes,artifacts:seamPolicySchema.properties.artifacts},['contractId','fromRevision','toRevision','actionId','actionRevision','step','expectedReviewRevision','decision','views','notes'])},
 {name:'reconstruct_motion',description:'Estimate a draft action from one person in a local video window (0.5–8 s): 2D pose, MotionBERT 3D lift, optional observation fit and retarget to the current rig. Stages are cached separately, so repeats and fit/phase changes skip finished inference. Returns a compact summary with stage timings, weak-observation times and artifact paths. commit:true saves the draft action and adds a motion-quality check. Output is an unreviewed estimate, never an approved movement.',inputSchema:object({video:{type:'string',minLength:1,maxLength:1024},start:{type:'number',minimum:0},end:{type:'number',minimum:0},detector:{enum:['yolo26s','yolo26n']},fit:{enum:['stable','fitted','none']},straightKneePrior:{type:'boolean',description:'Side-view assumption only: a confidently straight 2D knee is treated as straight in 3D.'},sourceSpeed:{type:'number',minimum:.1,maximum:1,description:'Playback speed of the footage relative to real time: 1 for real time, 0.4 for slow motion at 40%. The action is shortened to real time. Phases and corrections stay in footage seconds.'},decisions:{type:'boolean',description:'Ask a vision model (OpenRouter, needs OPENROUTER_API_KEY or OPENROUTER_ENV_FILE on the service) which way the performer faces and which leg is raised, about every 0.1 s, and use the answers to settle leg identity and turn direction. Sends cropped video frames to an external service; costs about a cent per clip.'},airborne:{type:'boolean',description:'Allow the character to leave the floor, using the pelvis rise in the image. Use for jumps filmed at a roughly constant distance.'},phases:{type:'array',minItems:1,maxItems:32,items:object({name:{type:'string',minLength:1,maxLength:48},end:{type:'number',description:'Phase end in clip seconds; the last must equal the window duration.'},kind:{enum:['move','fast','hold']}},['name','end'])},corrections:{type:'array',maxItems:8,description:'Bounded corrections to one body part in one clip-time window. smooth averages out jitter (strength 1–5); hold keeps the part in its pose from the window start. Nothing outside the part and window changes.',items:object({type:{enum:['smooth','hold']},part:{enum:Object.keys(bodyParts)},start:{type:'number',minimum:0},end:{type:'number',minimum:0},strength:{type:'integer',minimum:1,maximum:5}},['type','part','start','end'])},actionId:id,name:{type:'string',minLength:1,maxLength:80},force:{type:'boolean'},externalJoints:{type:'string',maxLength:1024,description:'Trial: path to a JSON file of 3D joints from another model (times, positions[frame][17][3] in H36M order, lift units and camera axes) that replace the lift before the fit.'},commit:{type:'boolean'},expectedRevision:expected},['video','start','end'])},
 {name:'inspect_video',description:'Read-only. Write a labelled contact sheet of a local video (or a window of it) so the frames and their timestamps can be read before choosing a reconstruction window. Returns the PNG path, the frame times, duration and frame size.',inputSchema:object({video:{type:'string',minLength:1,maxLength:1024},start:{type:'number',minimum:0},end:{type:'number',minimum:0},count:{type:'integer',minimum:4,maximum:40}},['video'])},
 {name:'compare_video_action',description:'Read-only. Write a review sheet for an action with a linked source video: video frames above the character from the front and side at the same clip times. Give explicit times (at most 12), or a start/end window and count. Returns the PNG path to inspect; it shows poses, not motion between them.',inputSchema:object({actionId:id,sourceRevision:expected,times:{type:'array',minItems:1,maxItems:12,items:{type:'number',minimum:0}},start:{type:'number',minimum:0},end:{type:'number',minimum:0},count:{type:'integer',minimum:2,maximum:12}},['actionId','sourceRevision'])},
 {name:'link_video_source',description:'Attach the local source video window an action was made from, so Studio Video review can play it beside the character. The window length must equal the action duration. The link is bound to the action revision; reconstruct_motion with commit:true links automatically.',inputSchema:object({actionId:id,expectedRevision:expected,video:{type:'string',minLength:1,maxLength:1024},start:{type:'number',minimum:0},end:{type:'number',minimum:0}})},
 {name:'inspect_motion_quality',description:'Read-only revision-pinned 60Hz rig inspection for movements or actions: rest bone/scale changes, candidate foot contacts, declared contact drift, root/pelvis travel and finite-difference seam velocities. Returns configured review flags and timestamps, never naturalness approval.',inputSchema:object({actionId:id,sourceRevision:expected,start:{type:'number',minimum:0,maximum:30},end:{type:'number',minimum:0,maximum:30},contacts:{type:'array',maxItems:16,items:object({foot:{enum:['left','right']},start:{type:'number',minimum:0,maximum:30},end:{type:'number',minimum:0,maximum:30}})},thresholds:object(Object.fromEntries(Object.keys(qualityDefaults).map(k=>[k,{type:'number'}])),[])},['actionId','sourceRevision'])},
 {name:'find_common_motion',description:'Read-only bounded search for shared motion windows between two revision-pinned movements on the current rig. Returns timestamps, normalized extraction ranges, pose errors and separate root travel. Excludes stationary holds by default; fixed-speed comparison, no provenance/contact guarantee.',inputSchema:object({movementA:id,revisionA:expected,movementB:id,revisionB:expected,bodyPart:{enum:['full','upper','lower']},minDuration:{type:'number',minimum:.1,maximum:10},positionTolerance:{type:'number',minimum:.001,maximum:.25},rotationTolerance:{type:'number',minimum:.1,maximum:45},limit:{type:'integer',minimum:1,maximum:10},includeHolds:{type:'boolean'}},['movementA','revisionA','movementB','revisionB'])},
 {name:'inspect_movement_library',description:'Read compact semantic manifests, source hashes, candidate continuation/recovery contracts, profiles and one-step draft specs. Unknown contacts stay unknown. No writes.',inputSchema:object({query:{type:'string',maxLength:200},limit:{type:'integer',minimum:1,maximum:50}},[])},
 {name:'build_action_spec',description:'Validate a typed semantic spec and revision/hash-pinned connections. commit false checks without writing; commit true compiles and saves once with a receipt. Reports structured diagnostics; physical/visual validation remains separate.',inputSchema:object({spec:actionSpecSchema,expectedRevision:expected,commit:{type:'boolean'}})},
 {name:'begin_action_run',description:'Start a timestamped prompt-to-action run. One active run at a time; subsequent MCP operations are automatically timed, including errors. Call at the beginning of a prompt.',inputSchema:object({prompt:{type:'string',minLength:1,maxLength:8000},actionId:id},['prompt'])},
 {name:'append_action_run_event',description:'Record an LLM decision, planning step or browser inspection at the current server UTC timestamp. Does not backdate events.',inputSchema:object({runId:str,phase:{type:'string',minLength:1,maxLength:64},note:{type:'string',minLength:1,maxLength:2000}})},
 {name:'finish_action_run',description:'Close a tracked run as completed, failed or cancelled with a final note and optional existing action ID.',inputSchema:object({runId:str,status:{enum:['completed','failed','cancelled']},note:{type:'string',minLength:1,maxLength:2000},actionId:id},['runId','status','note'])},
 {name:'list_action_runs',description:'List prompt-to-action run summaries, newest first. Optional action filter. Logs persist independently from motion data.',inputSchema:object({actionId:id},[])},
 {name:'get_action_run',description:'Fetch a run with every UTC timestamp, relative time, MCP service duration, result status and LLM notes.',inputSchema:object({runId:str})},
 {name:'revise_action_recipe',description:'Revise timings in an existing revision-pinned recipe, recompile, preserve the previous action as reference, and seek preview to the changed section in one operation. Duration sets total playback time for one movement; speed remains bounded 0.5–1.5. Source movements are unchanged.',inputSchema:object({actionId:id,expectedRevision:expected,changes:{type:'array',minItems:1,maxItems:8,items:object({step:{type:'integer',minimum:0,maximum:7},speed:{type:'number',minimum:.5,maximum:1.5},duration:{type:'number',minimum:.016,maximum:4},transition:{type:'number',minimum:0,maximum:1}},['step'])},playing:{type:'boolean'}},['actionId','expectedRevision','changes'])},
 {name:'profile_movement_library',description:'Measure current movement entry/exit poses, endpoint support hints and root/body travel on the actual rig. Saves revision-bound profiles without changing motions or movement revisions. Hints are not verified contacts.',inputSchema:object({expectedSequence:expected})},
 {name:'find_movement_connections',description:'Rank current profiled movement entries against a source exit. Heuristic pose/contact/travel evidence for LLM selection; not a physical guarantee.',inputSchema:object({movementId:id,sourceRevision:expected,limit:{type:'integer',minimum:1,maximum:20}},['movementId','sourceRevision'])},
 {name:'review_movement_profile',description:'Record endpoint support after visual inspection, with notes. Does not alter motion; profiles invalidate when the movement revision changes.',inputSchema:object({movementId:id,sourceRevision:expected,entrySupport:{enum:['both','left','right','none','unknown']},exitSupport:{enum:['both','left','right','none','unknown']},notes:{type:'string',minLength:1,maxLength:500}})},
 {name:'sync_movement_library',description:'Add missing adapted UAL2 Standard movements from the installed fixed source package. Never overwrites existing, edited or archived entries. Requires current project sequence.',inputSchema:object({library:{const:'ual2-standard'},expectedSequence:expected})},
 {name:'adapt_movement',description:'Trim and retime a library movement into a new record or revision, including all tracks, source segments and cues. No arbitrary joint generation. Source and destination revision checks.',inputSchema:object({sourceMovementId:id,sourceRevision:expected,movementId:id,name:str,from:{type:'number',minimum:0,maximum:1},to:{type:'number',minimum:0,maximum:1},speed:{type:'number',minimum:.5,maximum:1.5},expectedRevision:expected})},
 {name:'list_movements',description:'List library movements with revisions, source and contact metadata. Includes archived entries when requested.',inputSchema:object({includeArchived:{type:'boolean'}},[])},
 {name:'get_movement',description:'Read a base movement, metadata and revision before building or composing.',inputSchema:object({movementId:id})},
 {name:'register_movement',description:'Store or revise a verified Action v2 as a base movement. Use revision 0 for new records; movement IDs start with move-.',inputSchema:object({action:actionSchema,metadata:movementMetadataSchema,expectedRevision:expected})},
 {name:'build_movement',description:'Build a base movement from a discovered source clip segment, or an existing action. This tool does not import arbitrary models or generate motion.',inputSchema:object({movementId:id,name:str,clip:{enum:rigManifest.clips},sourceActionId:id,from:{type:'number',minimum:0,maximum:1},to:{type:'number',minimum:0,maximum:1},duration:{type:'number',minimum:.08,maximum:4},metadata:movementMetadataSchema,expectedRevision:expected},['movementId','name','metadata','expectedRevision'])},
 {name:'compose_action',description:'Create or revise a baked action from revision-pinned library movements with explicit pose-blend connection phases. Returns contact warnings; not an IK or balance solver.',inputSchema:object({actionId:id,name:str,steps:{type:'array',minItems:1,maxItems:8,items:object({movementId:id,revision:expected,speed:{type:'number',minimum:.5,maximum:1.5},transition:{type:'number',minimum:0,maximum:1},contact:{enum:['left','right']},blend:{enum:['pose','velocity']},travel:{enum:['source','continue']}},['movementId','revision','speed','transition'])},expectedRevision:expected})},
 {name:'archive_entry',description:'Archive or restore a library movement or action without deleting its data. Revision-checked and reversible.',inputSchema:object({entryId:id,archived:{type:'boolean'},expectedRevision:expected})},
 {name:'revise_kick',description:'Create or revise the authored kick study from immutable CC0 baseline. Bounded height correction preserves knee shape; release speed retimes all channels together. Reference stays the baseline.',inputSchema:object({heightDeg:{type:'number',minimum:-8,maximum:8},releaseSpeed:{type:'number',minimum:.75,maximum:1.25},expectedRevision:expected})},
 {name:'get_capabilities',description:'Discover all implemented rig, source clips, track schema, platform tools and limits. Read before authoring.',inputSchema:object({})},
 {name:'list_actions',description:'List persisted actions and revisions, including compact saved recipes for timing revisions.',inputSchema:object({})},
 {name:'get_action',description:'Read full action/reference and revision history. Fetch before a revision.',inputSchema:object({actionId:id})},
 {name:'create_action',description:'Create a new version-2 action and select it for live preview. Cannot overwrite existing IDs.',inputSchema:object({action:actionSchema})},
 {name:'revise_action',description:'Replace an action with fully authored data against expectedRevision. Previous action becomes comparison reference; undo history is retained. Accepts legacy version-1 data from get_action as well.',inputSchema:object({action:{type:'object'},expectedRevision:expected})},
 {name:'validate_action',description:'Validate complete authored data without changing the project.',inputSchema:object({action:actionSchema})},
 {name:'set_preview',description:'Control action selection, camera, playhead, playback, speed, loop, comparison, grid and impact visibility. Returns viewer URL.',inputSchema:previewSchema},
 {name:'get_diagnostics',description:'Measure root height and seven-joint RMS pose speed on the actual rig. Optionally return local/world joint transforms at a timestamp.',inputSchema:object({actionId:id,time:num},['actionId'])},
 {name:'capture_reference',description:'Copy the current action into its comparison reference.',inputSchema:object({actionId:id,expectedRevision:expected})},
 {name:'restore_revision',description:'Restore an earlier action revision as a new revision without deleting history.',inputSchema:object({actionId:id,revision:{type:'integer',minimum:1},expectedRevision:expected})},
 {name:'export_project',description:'Return portable project JSON, including current/reference pairs; asset remains a separate dependency.',inputSchema:object({})},
 {name:'import_project',description:'Import an Animation Studio project after validating all action/reference pairs. Existing actions become revisions; no arbitrary file paths.',inputSchema:object({project:{type:'object'},expectedSequence:{type:'integer',minimum:0}})},
];
export class Studio {
 path:string;state:any;asset:any;root:string;logs:RunLogs;contracts:ContractReviews;motionSignatures=new Map<string,MotionSignature>();legacy=false;blobs=new Set<string>();
 constructor(root:string,path=resolve(root,'.authoring/project.json')){this.root=root;this.path=path;this.logs=new RunLogs(path+'.runs.json');this.contracts=new ContractReviews(path+'.contracts.json');this.state={sequence:0,preview:{actionId:'jump',time:0,playing:false,speed:1,loop:true,view:'current',camera:'Orbit',grid:true,effects:true,idle:false,metric:'pose'},actions:{}};for(const a of [jump,burst])this.state.actions[a.id!]={revision:1,action:clone(a),reference:clone(a),history:[]};try{const loaded=loadProject(path);this.state=loaded.state;this.legacy=loaded.legacy;for(const pair of Object.values(this.state.actions) as any[]){validateAction(pair.action);validateAction(pair.reference);}}catch(e:any){if(e.code!=='ENOENT')throw e;}this.state.preview={idle:false,metric:'pose',...this.state.preview};try{const saved=JSON.parse(readFileSync(this.path+'.preview.json','utf8'));if(saved.sequence>=this.state.sequence&&this.state.actions[saved.preview.actionId]){this.state.sequence=saved.sequence;this.state.preview=saved.preview;}}catch(e:any){if(e.code!=='ENOENT')throw e;}let seeded=false;for(const m of seedMovements()){if(!this.state.actions[m.action.id!]){this.state.actions[m.action.id!]={revision:1,category:'movement',metadata:m.metadata,action:validateAction(m.action),reference:clone(m.action),history:[]};seeded=true;}}if(seeded){this.state.sequence++;this.persist();}}
 persist(){saveProject(this.path,this.state,this.blobs,this.legacy);this.legacy=false;}
 persistPreview(){mkdirSync(dirname(this.path),{recursive:true});const path=this.path+'.preview.json',tmp=path+'.tmp';writeFileSync(tmp,JSON.stringify({sequence:this.state.sequence,preview:this.state.preview}));renameSync(tmp,path);}
 snapshot(){return clone(this.state);}
 viewerSnapshot(){const entries=Object.entries(this.state.actions).map(([id,p]:any)=>{const full=id===this.state.preview.actionId;const summary=(a:any)=>full?a:{...a,tracks:a.version===2?[]:a.tracks};return [id,{...p,action:summary(p.action),reference:summary(p.reference),history:p.history.map((h:any)=>({revision:h.revision})),profile:p.profile?.sourceRevision===p.revision?p.profile:undefined,manifest:p.category==='movement'?manifest(id,p,this.contracts.data,this.state):undefined,previewOnly:!full}];});return clone({...this.state,actions:Object.fromEntries(entries)});}
 async linkVideo(actionId:string,file:string,sha256:string,window:number[],quality?:any){const p=this.pair(actionId),s=statSync(file);quality??=await this.execute('inspect_motion_quality',{actionId,sourceRevision:p.revision});p.videoSource={file,sha256,bytes:s.size,modifiedMs:s.mtimeMs,window,revision:p.revision,reviewWindows:(quality.inspectionWindows||[]).map((w:any)=>[w.start,w.end])};this.state.sequence++;this.persist();return {actionId,revision:p.revision,videoSource:p.videoSource};}
 pair(id:string){const p=Object.hasOwn(this.state.actions,id)?this.state.actions[id]:null;if(!p)throw Error('Unknown action ID');return p;}
 check(p:any,n:number){if(!Number.isInteger(n)||p.revision!==n)throw Error('Stale revision: read get_action again');}
 commit(a:Action,p?:any,save=true){const old=p&&clone(p);this.state.actions[a.id!]={revision:(p?.revision||0)+1,action:clone(a),reference:p?clone(p.action):clone(a),...(p?.category?{category:p.category,metadata:clone(p.metadata)}:{}),history:p?[...p.history,{revision:old.revision,action:old.action,...(old.motionParameters?{motionParameters:old.motionParameters}:{}),...(old.recipe?{recipe:old.recipe}:{}),...(old.semanticSpec?{semanticSpec:old.semanticSpec,buildReceipt:old.buildReceipt}:{}),...(old.metadata?{metadata:old.metadata}:{})}].slice(-100):[]};this.state.preview.actionId=a.id;this.state.preview.time=0;this.state.preview.playing=false;this.state.sequence++;if(save)this.persist();return clone(this.state.actions[a.id!]);}
 async compose(args:any,artifacts?:any){if(typeof args.actionId!=='string'||args.actionId.startsWith('move-')||!Array.isArray(args.steps))throw Error('Invalid composed action');const p=this.state.actions[args.actionId];if(p){if(p.category==='movement')throw Error('ID belongs to a movement');this.check(p,args.expectedRevision);}else if(args.expectedRevision!==0)throw Error('New action requires revision 0');const warnings:string[]=[],steps=args.steps.map((step:any,index:number)=>{if(Object.keys(step).some(k=>!['movementId','revision','speed','transition','contact','blend','travel'].includes(k)))throw Error('Invalid recipe step');const m=this.pair(step.movementId);if(m.category!=='movement'||m.archived)throw Error('Choose an active library movement');this.check(m,step.revision);if(index){const previous=this.pair(args.steps[index-1].movementId);if(previous.profile?.sourceRevision===previous.revision&&m.profile?.sourceRevision===m.revision){const match=compareEndpoints(previous.profile,m.profile);if(match.fit!=='near')warnings.push(`${m.action.name}: endpoint match needs inspection (${match.poseRmsMeters.toFixed(2)} m pose RMS, ${match.rotationRmsDegrees.toFixed(0)}° rotation RMS)`);if(!match.reviewed)warnings.push(`${m.action.name}: connection endpoints have not both been visually reviewed`);}}if(m.metadata.support==='unknown')warnings.push(`${m.action.name}: support/contact unverified`);if(m.metadata.travel==='source')warnings.push(`${m.action.name}: source travel retained; inspect root continuity`);return {action:clone(m.action),speed:step.speed,transition:step.transition,contact:step.contact,blend:step.blend,travel:step.travel};});if(!this.asset){const b=readFileSync(resolve(this.root,'editor/assets/character.glb'));this.asset=await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');}const model=cloneRig(this.asset.scene),holder=new THREE.Group();holder.add(model);const scale=1.85/new THREE.Box3().setFromObject(model).getSize(new THREE.Vector3()).y;holder.scale.setScalar(scale);const a=composeMovements(model,this.asset.animations,scale,args.actionId,args.name,steps);this.commit(a,p,false);const pair=this.pair(args.actionId);pair.recipe={steps:clone(args.steps),warnings,compiler:args.steps.some((s:any)=>s.blend==='velocity'||s.travel==='continue')?'pose-blend-v2':'pose-blend-v1'};if(artifacts){pair.semanticSpec=clone(artifacts.spec);pair.buildReceipt=clone(artifacts.receipt);}this.state.preview.idle=false;this.persist();return {actionId:a.id,revision:pair.revision,duration:duration(a),phases:a.phases.map(p=>({id:p.id,name:p.name,duration:p.duration})),recipe:pair.recipe};}
 async call(name:string,args:any={},transport='mcp'){
  const tracking=['begin_action_run','append_action_run_event','finish_action_run','list_action_runs','get_action_run'].includes(name);
  const runId=!tracking?this.logs.data.activeRunId:null;
  const startedAt=new Date().toISOString(),began=performance.now();
  const target=args?.actionId||args?.movementId||args?.action?.id;
  const event=runId?this.logs.event(runId,{source:'mcp',transport:transport==='cli'?'cli':'mcp',name:String(name).slice(0,80),phase:'tool',status:'running',startedAt,target:typeof target==='string'?target.slice(0,48):null}):null;
  try{const result=await this.execute(name,args);if(event){event.status=result?.valid===false?'failed':'completed';if(result?.valid===false)event.error=result.diagnostics?.filter((d:any)=>d.severity==='error').map((d:any)=>d.code+': '+d.message).join('; ').slice(0,1000);event.finishedAt=new Date().toISOString();event.elapsedMs=Math.round((performance.now()-began)*100)/100;event.revision=result?.revision??null;this.logs.save();}return result;}
  catch(error:any){if(event){event.status='failed';event.finishedAt=new Date().toISOString();event.elapsedMs=Math.round((performance.now()-began)*100)/100;event.error=String(error.message).slice(0,1000);this.logs.save();}throw error;}
 }
 async execute(name:string,args:any={}){
  if(!args||typeof args!=='object'||Array.isArray(args))throw Error('Arguments must be an object');
  const def=toolDefinitions.find(t=>t.name===name);if(!def)throw Error('Unknown tool');
  const required=(def.inputSchema as any).required||[];if(required.some((k:string)=>!(k in args))||Object.keys(args).some(k=>!(k in (def.inputSchema as any).properties)))throw Error('Invalid tool arguments');
  switch(name){
   case 'get_contract_reviews':{const data=clone(this.contracts.data);if(args.movementId){data.contacts=data.contacts.filter((r:any)=>r.movementId===args.movementId);data.contactHistory=data.contactHistory.filter((r:any)=>r.movementId===args.movementId);}if(args.contractId){data.seams=data.seams.filter((r:any)=>r.contractId===args.contractId);data.seamHistory=data.seamHistory.filter((r:any)=>r.contractId===args.contractId);}return data;}
   case 'review_movement_contacts':{const p=this.pair(args.movementId);this.check(p,args.sourceRevision);if(p.category!=='movement'||p.archived)throw Error('Choose an active movement');this.contracts.check('contacts',args.movementId,args.expectedReviewRevision);if(!Array.isArray(args.intervals)||!args.intervals.length||args.intervals.length>16)throw Error('Review 1–16 contact intervals');const report=await this.execute('inspect_motion_quality',{actionId:args.movementId,sourceRevision:p.revision,contacts:args.intervals.map((c:any)=>({foot:c.foot,start:c.start,end:c.end}))});const intervals=args.intervals.map((c:any,i:number)=>{if(Object.keys(c).some(k=>!['foot','start','end','decision','notes'].includes(k)))throw Error('Invalid contact interval fields');const measurements=report.declaredContacts[i];if(c.decision==='supported'&&(c.end-c.start+1e-9<report.thresholds.minContactDuration||measurements.maxHorizontalDriftMeters>report.thresholds.contactDriftTolerance||measurements.maxSpeedMetersPerSecond>report.thresholds.footSpeedTolerance||Math.max(Math.abs(measurements.minHeightMeters),Math.abs(measurements.maxHeightMeters))>report.thresholds.footHeightTolerance))throw Error('Supported contact exceeds measured height/speed/drift bounds; record uncertain or rejected instead');return {...c,measurements:Object.fromEntries(['maxHorizontalDriftMeters','pathMeters','maxSpeedMetersPerSecond','minHeightMeters','maxHeightMeters','sampleCount'].map(k=>[k,measurements[k]]))};});const result=this.contracts.put('contacts',args.movementId,args.expectedReviewRevision,{schemaVersion:1,movementId:args.movementId,sourceRevision:p.revision,motionHash:motionHash(p.action),intervals,reviewedAt:new Date().toISOString(),reviewer:'llm-visual',measurement:{algorithm:report.algorithm,sampleRate:report.sampleRate,measuredAt:report.measuredAt,thresholds:report.thresholds},views:args.views,notes:args.notes,artifacts:args.artifacts??[],physicalValidation:'not-performed',uncoveredIntervals:'unknown'});this.state.sequence++;this.persistPreview();return result;}
   case 'review_connection_policy':{const c=findContract(args.contractId);if(!c)throw Error('Unknown curated connection contract');const a=this.pair(c.from),b=this.pair(c.to),p=this.pair(args.actionId);this.check(a,args.fromRevision);this.check(b,args.toRevision);this.check(p,args.actionRevision);if(a.archived||b.archived||p.archived||motionHash(a.action)!==c.fromHash||motionHash(b.action)!==c.toHash)throw Error('Stale source contract or archived review action');this.contracts.check('seams',c.id,args.expectedReviewRevision);if(!Number.isInteger(args.step)||args.step<1||args.step>7)throw Error('Invalid recipe step');const previous=p.recipe?.steps[args.step-1],incoming=p.recipe?.steps[args.step];if(!previous||!incoming||previous.movementId!==c.from||incoming.movementId!==c.to||previous.revision!==a.revision||incoming.revision!==b.revision||incoming.contact)throw Error('Review requires matching pinned recipe pair without anchoring');let time=0,joinStart=-1,joinEnd=-1;for(const phase of p.action.phases){if(phase.id==='join-'+args.step){joinStart=time;joinEnd=time+phase.duration;}time+=phase.duration;}if(joinStart<0||Math.abs(joinEnd-joinStart-incoming.transition)>1e-6)throw Error('Compiled join does not match recipe');const report=await this.execute('inspect_motion_quality',{actionId:args.actionId,sourceRevision:p.revision,start:Math.max(0,joinStart-1/60),end:Math.min(duration(p.action),joinEnd+1/60)});const seams=report.seams.filter((s:any)=>Math.abs(s.time-joinStart)<1e-6||Math.abs(s.time-joinEnd)<1e-6);if(seams.length!==2)throw Error('Expected two measured join boundaries');if(args.decision==='supported'&&report.diagnostics.length)throw Error('Supported seam has configured review flags; record needs-review or rejected instead');const result=this.contracts.put('seams',c.id,args.expectedReviewRevision,{schemaVersion:1,contractId:c.id,fromRevision:a.revision,toRevision:b.revision,fromHash:motionHash(a.action),toHash:motionHash(b.action),decision:args.decision,configuration:{duration:incoming.transition,fromSpeed:previous.speed,toSpeed:incoming.speed,anchor:'none',...(incoming.blend?{blend:incoming.blend}:{}),...(incoming.travel?{travel:incoming.travel}:{})},evidenceAction:{id:args.actionId,revision:p.revision,motionHash:motionHash(p.action),step:args.step},seams:seams.map((s:any)=>Object.fromEntries(['time','rootVelocityJumpMetersPerSecond','jointVelocityJumpRmsMetersPerSecond','angularVelocityJumpRmsDegreesPerSecond'].map(k=>[k,s[k]]))),flagCodes:[...new Set(report.diagnostics.map((d:any)=>d.code))],reviewedAt:new Date().toISOString(),reviewer:'llm-visual',measurement:{algorithm:report.algorithm,sampleRate:report.sampleRate,measuredAt:report.measuredAt,thresholds:report.thresholds},views:args.views,notes:args.notes,artifacts:args.artifacts??[],physicalValidation:'not-performed'});this.state.sequence++;this.persistPreview();return result;}
   case 'inspect_video':{const file=isAbsolute(args.video)?args.video:resolve(this.root,args.video);let info;try{info=statSync(file);}catch{throw Error('Video file not found');}if(!info.isFile())throw Error('Video file not found');if(args.end!==undefined&&!(args.end>(args.start??0)))throw Error('end must be after start');const count=args.count??24,env=defaultEnvironment(this.root),out=resolve(this.root,'.authoring/review-sheets',`video-${(await hashFile(file)).slice(0,12)}-${args.start??0}-${args.end??'end'}-${count}.png`);return JSON.parse(await runProcess(env.python,[resolve(this.root,'authoring/reconstruction/sheets.py'),'overview','--video',file,'--out',out,'--start',String(args.start??0),...(args.end!==undefined?['--end',String(args.end)]:[]),'--count',String(count)],this.root));}
  case 'compare_video_action':{const p=this.pair(args.actionId);this.check(p,args.sourceRevision);const source=p.videoSource,total=duration(p.action);if(!source||source.revision!==p.revision)throw Error('No current source video is linked to this action; use link_video_source');const from=args.start??0,to=args.end??total;if(!(to>from)||to>total+1e-6)throw Error('Window must lie within the action');const count=args.count??8,times=(args.times??Array.from({length:count},(_,i)=>from+(to-from)*i/(count-1))).map((t:number)=>Math.round(Math.min(total,t)*1000)/1000);if(times.some((t:number)=>!Number.isFinite(t)||t<0))throw Error('Times must lie within the action');const env=defaultEnvironment(this.root),key=digest({id:args.actionId,revision:p.revision,times}).slice(0,12),work=resolve(this.root,'.authoring/review-sheets',`work-${key}`),out=resolve(this.root,'.authoring/review-sheets',`${args.actionId}-r${p.revision}-${key}.png`);mkdirSync(work,{recursive:true});writeFileSync(resolve(work,'action.json'),JSON.stringify(p.action));writeFileSync(resolve(work,'cases.json'),JSON.stringify([[p.action.id,times]]));await runProcess(process.execPath,[resolve(this.root,'authoring/reconstruction/capture-draft.mjs'),resolve(work,'frames'),resolve(work,'cases.json'),resolve(work,'action.json'),'--follow-root'],this.root);const sheet=JSON.parse(await runProcess(env.python,[resolve(this.root,'authoring/reconstruction/sheets.py'),'compare','--video',source.file,'--out',out,'--start',String(source.window[0]),'--scale',String((source.window[1]-source.window[0])/total),'--times',times.join(','),'--frames',resolve(work,'frames'),'--id',p.action.id!],this.root));rmSync(work,{recursive:true,force:true});return {actionId:args.actionId,revision:p.revision,file:sheet.file,times,rows:['source video','character front','character side'],note:'Sampled poses only; check motion between them in Studio Video review.'};}
  case 'link_video_source':{const p=this.pair(args.actionId);this.check(p,args.expectedRevision);if(p.archived)throw Error('Choose an active action');if(typeof args.video!=='string'||![args.start,args.end].every(Number.isFinite)||Math.abs(args.end-args.start-duration(p.action))>1e-3)throw Error('Video window must match the action duration '+duration(p.action).toFixed(3)+' s');const file=isAbsolute(args.video)?args.video:resolve(this.root,args.video);let size;try{size=statSync(file);}catch{throw Error('Video file not found');}if(!size.isFile())throw Error('Video file not found');return this.linkVideo(args.actionId,file,await hashFile(file),[args.start,args.end]);}
  case 'reconstruct_motion':{const {commit=false,expectedRevision,...request}=args;if(typeof commit!=='boolean')throw Error('commit must be a boolean');const actionId=request.actionId??'video-reconstruction-draft';const destination=()=>{const p=Object.hasOwn(this.state.actions,actionId)?this.state.actions[actionId]:null;if(p){if(p.category==='movement'||p.archived)throw Error('Choose a new or active non-movement action ID');this.check(p,expectedRevision);}else if(expectedRevision!==undefined&&expectedRevision!==0)throw Error('New action requires revision 0');return p;};if(commit)destination();if(!this.asset){const bytes=readFileSync(resolve(this.root,'editor/assets/character.glb'));this.asset=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');}const {summary,action}=await reconstruct(this.root,request,{retarget:(ir:any,r:any)=>{const model=cloneRig(this.asset.scene),holder=new THREE.Group();holder.add(model);const scale=1.85/new THREE.Box3().setFromObject(model).getSize(new THREE.Vector3()).y;holder.scale.setScalar(scale);new CharacterPlayer(model,this.asset.animations,scale).sample({version:2,rig:'quaternius-ual1',id:'retarget-rest',name:'Rest',phases:[{id:'rest',name:'Rest',intent:'Rest',duration:1,clip:'A_TPose',from:0,to:0}],tracks:[]} as any,0);if(!(ir.firstBoxHeightPixels>0))throw Error('Observation has no subject height');return retargetMotion(model,ir.rootRelativePositions,ir.times.map((t:number)=>t*r.sourceSpeed),ir.imagePelvis,1.85/ir.firstBoxHeightPixels,r.actionId,{name:r.name,airborne:r.airborne,lowestAnkleImageY:ir.lowestSupportImageY??ir.lowestAnkleImageY,lowestIsBody:ir.lowestSupportSource==='body',faceDirection:ir.faceDirection,phases:r.phases?.map((p:any)=>({...p,end:p.end*r.sourceSpeed}))});}});if(!commit)return summary;const saved=this.commit(validateAction(action),destination()||undefined),quality=await this.execute('inspect_motion_quality',{actionId,sourceRevision:saved.revision});await this.linkVideo(actionId,summary.video.file,summary.video.sha256,summary.video.window,quality);return {...summary,actionId,revision:saved.revision,quality:{status:quality.status,inspectionWindows:quality.inspectionWindows}};}
  case 'inspect_motion_quality':{const began=performance.now(),p=this.pair(args.actionId);if(p.archived)throw Error('Choose an active movement or action');this.check(p,args.sourceRevision);qualityRequest(duration(p.action),args);if(!this.asset){const bytes=readFileSync(resolve(this.root,'editor/assets/character.glb'));this.asset=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');}const model=cloneRig(this.asset.scene),holder=new THREE.Group();holder.add(model);const scale=1.85/new THREE.Box3().setFromObject(model).getSize(new THREE.Vector3()).y;holder.scale.setScalar(scale);const report=inspectMotionQuality(new CharacterPlayer(model,this.asset.animations,scale),p.action,args,p.recipe);return {actionId:args.actionId,revision:p.revision,motionHash:motionHash(p.action),rig:'quaternius-ual1',measuredAt:new Date().toISOString(),...report,elapsedMs:Math.round((performance.now()-began)*100)/100};}
   case 'find_common_motion':{const began=performance.now(),pairs=[this.pair(args.movementA),this.pair(args.movementB)];pairs.forEach((p,i)=>{if(p.category!=='movement'||p.archived)throw Error('Choose active library movements');this.check(p,i===0?args.revisionA:args.revisionB);if(duration(p.action)>30)throw Error('Comparison supports movements up to 30 seconds');});
    // Validate options before any expensive sampling.
    compareMotion({duration:1,times:[],poses:[],roots:[]},{duration:1,times:[],poses:[],roots:[]},args);
    const sources=pairs.map((p,i)=>({id:i===0?args.movementA:args.movementB,revision:p.revision,motionHash:motionHash(p.action)}));let sampled=0;
    for(let i=0;i<2;i++){const key=sources[i].motionHash;if(this.motionSignatures.has(key)){const cached=this.motionSignatures.get(key)!;this.motionSignatures.delete(key);this.motionSignatures.set(key,cached);continue;}if(!this.asset){const bytes=readFileSync(resolve(this.root,'editor/assets/character.glb'));this.asset=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');}const model=cloneRig(this.asset.scene),holder=new THREE.Group();holder.add(model);const scale=1.85/new THREE.Box3().setFromObject(model).getSize(new THREE.Vector3()).y;holder.scale.setScalar(scale);this.motionSignatures.set(key,sampleSignature(new CharacterPlayer(model,this.asset.animations,scale),pairs[i].action));sampled++;if(this.motionSignatures.size>6)this.motionSignatures.delete(this.motionSignatures.keys().next().value!);}
    const result=compareMotion(this.motionSignatures.get(sources[0].motionHash)!,this.motionSignatures.get(sources[1].motionHash)!,args);return {schemaVersion:1,sources,...result,sampledMovements:sampled,elapsedMs:Math.round(performance.now()-began),extraction:'For a reviewed full-body match, use adapt_movement with the returned from/to and pinned source revision; no automatic library writes.'};}
   case 'inspect_movement_library':return inspectLibrary(this.state,args,this.contracts.data);
   case 'build_action_spec':{const began=performance.now(),checked=resolveSpec(this.state,args.spec,args.expectedRevision,args.commit,this.contracts.data);if(!checked.valid||!args.commit)return {...checked,committed:false};const receipt={...checked.receipt,compiledAt:new Date().toISOString()};try{const result=await this.compose({actionId:args.spec.id,name:args.spec.name,steps:checked.steps,expectedRevision:args.expectedRevision},{spec:args.spec,receipt});return {...result,valid:true,committed:true,diagnostics:checked.diagnostics,receipt,elapsedMs:Math.round(performance.now()-began)};}catch(e:any){return {valid:false,committed:false,diagnostics:[...checked.diagnostics,{code:'compiler/failed',severity:'error',subject:'/steps',message:e.message,evidence:null,supportedFixes:['Revise specification using compiler limits']}],receipt:checked.receipt};}}
   case 'begin_action_run':return this.logs.begin(args.prompt,args.actionId);
   case 'append_action_run_event':return this.logs.append(args.runId,args.phase,args.note);
   case 'finish_action_run':{const run=this.logs.run(args.runId),target=args.actionId||run.actionId;const pair=target&&(args.status==='completed'||args.actionId)?this.pair(target):null;const result=this.logs.finish(args.runId,args.status,args.note,args.actionId);if(pair){run.actionRevision=pair.revision;this.logs.save();}return {...result,actionRevision:run.actionRevision??null};}
   case 'list_action_runs':return this.logs.list(args.actionId);
   case 'get_action_run':return this.logs.get(args.runId);
   case 'revise_action_recipe':{const began=performance.now(),p=this.pair(args.actionId);this.check(p,args.expectedRevision);if(p.archived||p.category==='movement'||!p.recipe)throw Error('Choose an active action with a saved recipe');if(!Array.isArray(args.changes)||!args.changes.length||args.changes.length>8||args.playing!==undefined&&typeof args.playing!=='boolean')throw Error('Invalid recipe changes');const oldAction=p.action,steps=clone(p.recipe.steps),seen=new Set<number>(),changes:any[]=[];
    for(const change of args.changes){if(!change||Object.keys(change).some(k=>!['step','speed','duration','transition'].includes(k))||!Number.isInteger(change.step)||change.step<0||change.step>=steps.length||seen.has(change.step)||Object.keys(change).length===1||change.speed!==undefined&&change.duration!==undefined)throw Error('Choose unique valid step indices and either speed or duration');seen.add(change.step);const step=steps[change.step],before=clone(step);if(change.speed!==undefined){if(!Number.isFinite(change.speed)||change.speed<.5||change.speed>1.5)throw Error('Speed must be 0.5–1.5');step.speed=change.speed;}if(change.duration!==undefined){if(!Number.isFinite(change.duration)||change.duration<.016||change.duration>4)throw Error('Invalid movement duration');const speed=duration(this.pair(step.movementId).action)/change.duration;if(speed<.5-1e-9||speed>1.5+1e-9)throw Error('Requested duration needs speed outside 0.5–1.5; prepare a new movement variant');step.speed=Math.max(.5,Math.min(1.5,speed));}if(change.transition!==undefined){if(!Number.isFinite(change.transition)||change.transition<0||change.transition>1||change.step===0&&change.transition!==0||change.step>0&&change.transition===0)throw Error('Use first transition 0 and later transitions greater than 0, at most 1 second');step.transition=change.transition;}changes.push({step:change.step,movementId:step.movementId,before,after:clone(step)});}
    if(changes.every(c=>JSON.stringify(c.before)===JSON.stringify(c.after)))throw Error('No recipe timing changes');const range=(a:Action)=>{let time=0,start=Infinity,end=0;for(const phase of a.phases){const affected=[...seen].some(i=>phase.id.startsWith('m'+i+'-')||phase.id==='join-'+i||phase.id==='join-'+(i+1));if(affected){start=Math.min(start,time);end=time+phase.duration;}time+=phase.duration;}return {start:Number.isFinite(start)?start:0,end};};const previous=range(oldAction);const result=await this.execute('compose_action',{actionId:args.actionId,name:oldAction.name,expectedRevision:args.expectedRevision,steps});const inspection=range(this.pair(args.actionId).action);this.state.preview={...this.state.preview,time:inspection.start,idle:false,playing:args.playing??false,loop:false};this.persistPreview();return {...result,changes,inspection:{...inspection,previousStart:previous.start,previousEnd:previous.end},elapsedMs:Math.round(performance.now()-began),viewerUrl:'http://127.0.0.1:5173/editor/'};}

   case 'profile_movement_library':{if(args.expectedSequence!==this.state.sequence)throw Error('Stale project sequence');if(!this.asset){const b=readFileSync(resolve(this.root,'editor/assets/character.glb'));this.asset=await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');}const model=cloneRig(this.asset.scene),holder=new THREE.Group();holder.add(model);const scale=1.85/new THREE.Box3().setFromObject(model).getSize(new THREE.Vector3()).y;holder.scale.setScalar(scale);const player=new CharacterPlayer(model,this.asset.animations,scale);const profiled:string[]=[];for(const [id,p]of Object.entries(this.state.actions) as [string,any][]){if(p.category!=='movement'||p.archived||p.profile?.sourceRevision===p.revision)continue;p.profile=profileMovement(player,p.action,p.revision);profiled.push(id);}if(profiled.length){this.state.sequence++;this.persist();}return {profiled,sequence:this.state.sequence,note:'Support hints are measured, not verified contacts; review before anchoring.'};}
   case 'find_movement_connections':{const p=this.pair(args.movementId);this.check(p,args.sourceRevision);if(p.archived||p.category!=='movement'||p.profile?.sourceRevision!==p.revision)throw Error('Profile the active source movement first');const limit=args.limit??8;if(!Number.isInteger(limit)||limit<1||limit>20)throw Error('Limit must be 1–20');return Object.entries(this.state.actions).filter(([_,m]:any)=>m.category==='movement'&&!m.archived&&m.profile?.sourceRevision===m.revision).map(([id,m]:any)=>({movementId:id,name:m.action.name,revision:m.revision,...compareEndpoints(p.profile,m.profile),entry:m.profile.entry.pose,travel:m.profile.travel})).sort((a,b)=>a.score-b.score).slice(0,limit);}
   case 'review_movement_profile':{const p=this.pair(args.movementId);this.check(p,args.sourceRevision);if(p.archived||p.category!=='movement'||p.profile?.sourceRevision!==p.revision)throw Error('Profile the active movement first');if(!['both','left','right','none','unknown'].includes(args.entrySupport)||!['both','left','right','none','unknown'].includes(args.exitSupport)||typeof args.notes!=='string'||!args.notes.trim()||args.notes.length>500)throw Error('Invalid endpoint review');p.profile.review={entrySupport:args.entrySupport,exitSupport:args.exitSupport,notes:args.notes};this.state.sequence++;this.persist();return clone(p.profile);}

   case 'sync_movement_library':{if(args.library!=='ual2-standard'||args.expectedSequence!==this.state.sequence)throw Error('Unknown library or stale project sequence');const entries=ual2Library.movements.map(m=>({action:validateAction(m.action),metadata:movementMetadata(m.metadata)}));const added:string[]=[],kept:string[]=[];for(const m of entries){const id=m.action.id!;if(this.state.actions[id]){kept.push(id);continue;}this.state.actions[id]={revision:1,category:'movement',metadata:m.metadata,action:m.action,reference:clone(m.action),history:[]};added.push(id);}if(added.length){this.state.sequence++;this.persist();}return {library:args.library,sourceHash:ual2Library.sourceHash,added,kept,sequence:this.state.sequence};}
   case 'adapt_movement':{const source=this.pair(args.sourceMovementId);if(source.category!=='movement'||source.archived)throw Error('Choose an active source movement');this.check(source,args.sourceRevision);const action=adaptMovement(source.action,args.movementId,args.name,args.from,args.to,args.speed);const metadata={...source.metadata,notes:(source.metadata.notes+' Adapted range '+args.from+'–'+args.to+', speed '+args.speed+'×; source '+args.sourceMovementId+' r'+args.sourceRevision).slice(0,500)};return this.execute('register_movement',{action,metadata,expectedRevision:args.expectedRevision});}

   case 'list_movements':return Object.entries(this.state.actions).filter(([_,p]:any)=>p.category==='movement'&&(args.includeArchived||!p.archived)).map(([id,p]:any)=>({id,name:p.action.name,revision:p.revision,duration:duration(p.action),metadata:p.metadata,profile:p.profile?.sourceRevision===p.revision?p.profile:null,archived:!!p.archived}));
   case 'get_movement':{const p=this.pair(args.movementId);if(p.category!=='movement')throw Error('Not a base movement');return {...clone(p),contactReview:contactReview(args.movementId,p,this.contracts.data)};}
   case 'archive_entry':{if(['jump','burst'].includes(args.entryId))throw Error('Built-in demo actions cannot be archived');const p=this.pair(args.entryId);this.check(p,args.expectedRevision);if(typeof args.archived!=='boolean')throw Error('Invalid archive control');p.archived=args.archived;p.revision++;if(p.archived&&this.state.preview.actionId===args.entryId){this.state.preview.actionId='jump';this.state.preview.time=0;this.state.preview.playing=false;}this.state.sequence++;this.persist();return {revision:p.revision,archived:p.archived};}
   case 'build_movement':{if(!!args.clip===!!args.sourceActionId)throw Error('Choose exactly one source clip or source action');let action:Action;if(args.sourceActionId){const source=this.pair(args.sourceActionId);if(source.archived)throw Error('Source is archived');if(args.from!==undefined||args.to!==undefined||args.duration!==undefined)throw Error('Action sources copy complete motion; use clip segments for trimming');action=clone(source.action);if(action.version!==2)throw Error('Use a version-2 source action');action.id=args.movementId;action.name=args.name;}else{const from=args.from??0,to=args.to??1,total=args.duration??((to-from)*(rigManifest.clipDurations as any)[args.clip]);if(!(to>from))throw Error('Use an increasing source segment');action={version:2,rig:'quaternius-ual1',id:args.movementId,name:args.name,phases:[{id:'motion',name:args.name,intent:'Source motion segment',duration:total,kind:'move',clip:args.clip,from,to}],tracks:[],cues:[]};}return this.execute('register_movement',{action,metadata:args.metadata,expectedRevision:args.expectedRevision});}
   case 'register_movement':{const a=validateAction(args.action),meta=movementMetadata(args.metadata);if(a.version!==2||!a.id?.startsWith('move-'))throw Error('Base movement IDs start with move-');const p=this.state.actions[a.id];if(p){if(p.category!=='movement')throw Error('ID belongs to an action');this.check(p,args.expectedRevision);}else if(args.expectedRevision!==0)throw Error('New movement requires revision 0');this.commit(a,p);const pair=this.pair(a.id);pair.category='movement';pair.metadata=meta;this.persist();return {movementId:a.id,revision:pair.revision,duration:duration(a),metadata:meta};}
   case 'compose_action':return this.compose(args);

   case 'get_capabilities':return {semanticAuthoring:{schemaVersion:1,conventions,actionSpecSchema,tools:['inspect_movement_library','build_action_spec','find_common_motion','inspect_motion_quality','reconstruct_motion','link_video_source','inspect_video','compare_video_action','review_movement_contacts','review_connection_policy','get_contract_reviews'],limitations:'Whole movement windows only; positive pose blends; candidate contracts; no verified contact or arbitrary retargeting'},manifest:rigManifest,projectSequence:this.state.sequence,movementProfiles:{jointOrder:['pelvis','spine_03','Head','upperarm_l','lowerarm_l','hand_l','upperarm_r','lowerarm_r','hand_r','thigh_l','calf_l','foot_l','thigh_r','calf_r','foot_r'],units:'World distances in normalized meters; local joint quaternions; positions relative to model root',forward:'Model +Z axis transformed by model root rotation; not an inferred anatomical facing',supportHints:'Ball joint within 0.05 m of floor and speed <=0.15 m/s over up to 0.05 s; none means no stationary foot detected, not absence of hand/body contact',matching:'Endpoint heuristic, not complete motion validation. Profiles and reviews invalidate on movement revision. Refresh after import.'},sourceLibraries:[{id:'ual2-standard',clips:ual2Library.movements.length,license:'CC0-1.0',sourceHash:ual2Library.sourceHash}],movementLibrary:{tools:['profile_movement_library','find_movement_connections','review_movement_profile','sync_movement_library','adapt_movement','list_movements','get_movement','build_movement','register_movement','compose_action','revise_action_recipe','archive_entry'],composition:'Revision-pinned recipe, explicit connection phases, baked tracks, maximum 4 seconds; smooth pose blending with optional single-foot whole-body anchoring; no IK or balance solver'},kickStudy:{controls:kickLimits,source:'Mesh2Motion Kick_Breach (CC0)',tool:'revise_kick',limitations:'Bounded forward kick only; no general IK, collision or automatic balance solver'},actionSchema,tools:toolDefinitions,viewerUrl:'http://127.0.0.1:5174/editor/',notes:['Version 2 can author all discovered joint channels and new phase sequences.','Version 1 Jump/Burst remain compatible.','Rotations use shortest-path quaternion slerp. Offset is post-multiplied on the sampled clip pose.','Root tracks use normalized runtime meters. Choose in-place source clips to avoid double movement.','All writes persist automatically; revision history is retained up to 100 per action.']};
   case 'revise_kick':{const p=this.state.actions['kick-study'];if(p)this.check(p,args.expectedRevision);else if(args.expectedRevision!==0)throw Error('New kick requires revision 0');if(!this.asset){const b=readFileSync(resolve(this.root,'editor/assets/character.glb'));this.asset=await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');}const model=cloneRig(this.asset.scene),holder=new THREE.Group();holder.add(model);const scale=1.85/new THREE.Box3().setFromObject(model).getSize(new THREE.Vector3()).y;holder.scale.setScalar(scale);const parameters={heightDeg:args.heightDeg,releaseSpeed:args.releaseSpeed};const a=compileKick(model,this.asset.animations,scale,parameters);this.commit(a,p);const pair=this.pair('kick-study');pair.reference=clone(kickBaseline);pair.motionParameters=parameters;this.state.preview.time=.78;this.state.preview.idle=false;this.persist();return {revision:pair.revision,parameters,duration:duration(a)};}
   case 'list_actions':return Object.entries(this.state.actions).filter(([_,p]:any)=>p.category!=='movement'&&!p.archived).map(([id,p]:any)=>({id,name:p.action.name,revision:p.revision,version:p.action.version,duration:duration(p.action),...(p.recipe?{recipe:p.recipe}:{}),...(p.semanticSpec?{semanticSpec:p.semanticSpec,buildReceipt:p.buildReceipt}:{})}));
   case 'get_action':{const p=clone(this.pair(args.actionId));p.history=p.history.map((h:any)=>({revision:h.revision,name:h.action.name,duration:duration(h.action)}));return p;}
   case 'validate_action':return {valid:true,action:validateAction(args.action),duration:duration(args.action)};
   case 'create_action':{const a=validateAction(args.action);if(a.id?.startsWith('move-'))throw Error('Use register_movement for base movement IDs');if(a.version!==2||Object.hasOwn(this.state.actions,a.id!))throw Error('Use a new version-2 action ID');return this.commit(a);}
   case 'revise_action':{const a=validateAction(args.action);a.id=a.id||'jump';const p=this.pair(a.id!);if(p.category==='movement')throw Error('Use register_movement to revise base movements');this.check(p,args.expectedRevision);return this.commit(a,p);}
   case 'set_preview':{const p={...this.state.preview,...args};if(this.pair(p.actionId).archived)throw Error('Entry is archived');if(!['current','reference','both'].includes(p.view)||!['Orbit','Front','Side','Top'].includes(p.camera)||['playing','loop','grid','effects','idle'].some(k=>typeof p[k]!=='boolean')||!Number.isFinite(p.time)||p.time<0||p.time>30||!Number.isFinite(p.speed)||p.speed<.05||p.speed>2)throw Error('Invalid preview controls');if(!['pose','height'].includes(p.metric))throw Error('Invalid diagnostic graph');p.time=Math.min(p.time,Math.max(duration(this.pair(p.actionId).action),duration(this.pair(p.actionId).reference)));this.state.preview=p;this.state.sequence++;this.persistPreview();return {preview:clone(p),viewerUrl:'http://127.0.0.1:5174/editor/'};}
   case 'capture_reference':{const p=this.pair(args.actionId);this.check(p,args.expectedRevision);p.history=[...p.history,{revision:p.revision,action:clone(p.action),...(p.recipe?{recipe:clone(p.recipe)}:{}),...(p.metadata?{metadata:clone(p.metadata)}:{}),...(p.motionParameters?{motionParameters:clone(p.motionParameters)}:{})}].slice(-100);p.reference=clone(p.action);p.revision++;this.state.sequence++;this.persist();return clone(p);}
   case 'restore_revision':{const p=this.pair(args.actionId);this.check(p,args.expectedRevision);const h=p.history.find((h:any)=>h.revision===args.revision);if(!h)throw Error('Revision not in retained history');const result=this.commit(h.action,p);if(h.recipe||h.metadata||h.semanticSpec){const pair=this.pair(args.actionId);if(h.semanticSpec){pair.semanticSpec=clone(h.semanticSpec);pair.buildReceipt=clone(h.buildReceipt);}if(h.recipe)pair.recipe=clone(h.recipe);if(h.metadata)pair.metadata=clone(h.metadata);this.persist();}if(h.motionParameters){const pair=this.pair(args.actionId);pair.motionParameters=clone(h.motionParameters);pair.reference=clone(kickBaseline);this.persist();return clone(pair);}return clone(this.pair(args.actionId));}
   case 'export_project':{const actions=Object.fromEntries(Object.entries(this.state.actions).map(([id,p]:any)=>[id,{action:p.action,reference:p.reference,...(p.motionParameters?{motionParameters:p.motionParameters}:{}),...(p.category?{category:p.category,metadata:p.metadata,...(p.profile?.sourceRevision===p.revision?{profile:p.profile}:{})}:{}),...(p.recipe?{recipe:p.recipe}:{}),...(p.semanticSpec?{semanticSpec:p.semanticSpec,buildReceipt:p.buildReceipt}:{}),...(p.archived?{archived:true}:{})}]));const pair=this.pair(this.state.preview.actionId);return {app:'animation-studio',version:1,...clone({action:pair.action,reference:pair.reference,actions,contracts:this.contracts.data})};}
   case 'import_project':{if(args.expectedSequence!==this.state.sequence)throw Error('Stale project sequence');const doc=args.project;if(doc?.app!=='animation-studio'||doc.version!==1)throw Error('Unknown project');if(doc.contracts)validateReviewData(doc.contracts);const active=validateAction(doc.action),ref=validateAction(doc.reference);if((active.id||'jump')!==(ref.id||'jump'))throw Error('Reference identity mismatch');for(const [id,p]of Object.entries(doc.actions||{}) as [string,any][]){const a=validateAction(p.action),r=validateAction(p.reference);if(p.recipe)validateRecipe(p.recipe);if(p.category!==undefined&&p.category!=='movement')throw Error('Unknown library category');if(p.category==='movement'){if(!id.startsWith('move-'))throw Error('Invalid movement ID');movementMetadata(p.metadata);}if((a.id||'jump')!==id||(r.id||'jump')!==id)throw Error('Library identity mismatch');}const library={...(doc.actions||{}),[active.id||'jump']:{...(doc.actions?.[active.id||'jump']||{}),action:active,reference:ref}};const pairs=Object.entries(library).map(([id,p]:any)=>{const a=validateAction(p.action),r=validateAction(p.reference);if(p.recipe)validateRecipe(p.recipe);if(p.category!==undefined&&p.category!=='movement')throw Error('Unknown library category');if(p.category==='movement'){if(!id.startsWith('move-'))throw Error('Invalid movement ID');movementMetadata(p.metadata);}if((a.id||'jump')!==id||(r.id||'jump')!==id)throw Error('Library identity mismatch');return [id,a,r] as const;});for(const [id,a,r]of pairs){this.commit({...a,id},this.state.actions[id]);this.state.actions[id].reference=r;const entry=library[id];if(entry.category==='movement'){this.state.actions[id].category='movement';this.state.actions[id].metadata=movementMetadata(entry.metadata);}if(entry.recipe)this.state.actions[id].recipe=validateRecipe(entry.recipe);this.state.actions[id].archived=!!entry.archived;const params=library[id].motionParameters;if(id==='kick-study'&&params&&Number.isFinite(params.heightDeg)&&Math.abs(params.heightDeg)<=8&&Number.isFinite(params.releaseSpeed)&&params.releaseSpeed>=.75&&params.releaseSpeed<=1.25)this.state.actions[id].motionParameters=clone(params);}this.state.preview.actionId=active.id||'jump';this.persist();if(doc.contracts)this.contracts.import(doc.contracts);return this.snapshot();}
   case 'get_diagnostics':{const p=this.pair(args.actionId);if(args.time!==undefined&&(!Number.isFinite(args.time)||args.time<0||args.time>duration(p.action)))throw Error('Timestamp outside action');if(!this.asset){const b=readFileSync(resolve(this.root,'editor/assets/character.glb'));this.asset=await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');}const model=cloneRig(this.asset.scene),holder=new THREE.Group();holder.add(model);const scale=1.85/new THREE.Box3().setFromObject(model).getSize(new THREE.Vector3()).y;holder.scale.setScalar(scale);const player=new CharacterPlayer(model,this.asset.animations,scale);const speeds=player.poseSpeeds(p.action),total=duration(p.action),height=speeds.map((_:any,i:number)=>rootHeight(p.action,Math.min(i/60,total)));const out:any={revision:p.revision,duration:total,sampleRate:60,poseSpeedMetric:'7-joint RMS m/s; root translation removed',poseSpeed:speeds,rootHeight:height,warnings:height.some((h:number)=>h<0)?['Root trajectory goes below floor']:[]};if(args.time!==undefined){player.sample(p.action,args.time);out.joints=rigManifest.bones.map(b=>{const n=model.getObjectByName(b.name)!;return {name:b.name,localPosition:n.position.toArray(),localRotation:n.quaternion.toArray(),localScale:n.scale.toArray(),worldPosition:n.getWorldPosition(new THREE.Vector3()).toArray()};});}return out;}
  }
 }
}
